### ISSUE TITLE
“ua help” links to non-existent ubuntu.com/cis-audit

### ISSUE THREAD

**Issue by matthewpaulthomas** [CanonicalLtd/ubuntu-advantage-client#1001]
ua 19.6~ubuntu14.04.4

1\. `ua help`

What you see:
```
usage: ua [command] [flags]

Client to manage Ubuntu Advantage services on a machine.
 - cc-eal: Common Criteria EAL2 Provisioning Packages
   (https://ubuntu.com/cc-eal)
 - cis-audit: Center for Internet Security Audit Tools
   (https://ubuntu.com/cis-audit)
…
```

What’s wrong with this: https://ubuntu.com/cis-audit returns a 404 error. As far as I can tell, the page has never existed, and there is no current request for it to be created.

If you would like this page to exist, please [submit a brief to the Web team](https://docs.google.com/document/d/1YOUAdRB7YYRZA8kyeu199KbWdR-rT8Kkml3eG3CRs8A/edit). In the meantime, please remove this link.

**Comment by matthewpaulthomas** [comment]
On further investigation, the CIS benchmark is described at the bottom of [ubuntu.com/security/certifications](https://ubuntu.com/security/certifications), which is where ubuntu.com/cc-eal and ubuntu.com/fips redirect to. So, I’ve submitted [a change to redirect there from ubuntu.com/cis-audit as well](https://github.com/canonical-web-and-design/ubuntu.com/pull/6711).

Unless that redirect used to exist, it is still a concern that a link to a non-working URL passed code review.

**Comment by powersj** [comment]
Thanks for creating the alias for now.

Looks like https://github.com/CanonicalLtd/ubuntu-advantage-client/commit/2500337aa7dd98ee3cb351dabaf9e1c1ca01f5d7 was the offending commit. It was during the mass rename of all the services.

I am going to close this as the root issue was solved.
