### ISSUE TITLE
crash in log of cloned Pro instance: uaclient.exceptions.AlreadyAttachedError: <uaclient.config.UAConfig object at 0xfoo>

### ISSUE THREAD

**Issue by cmars** [CanonicalLtd/ubuntu-advantage-client#1015]
Originally reported here: https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1867573.

Basically, if one clones a Pro image with packer, it retains the marketplaceProductCodes, which would grant it a new contract token on auto-attach. The client needs to detect when this happens -- a change in instance ID would work, for example -- then discard any prior attachement, and re-attempt the auto-attach as if it were a fresh instance.

**Comment by powersj** [comment]
Closed in #1016
