### ISSUE TITLE
Missing GPG keyring error when trying to enable fips

### ISSUE THREAD

**Issue by cmars** [CanonicalLtd/ubuntu-advantage-client#1026]
When I try to enable FIPS on xenial (with a contract entitled to `fips`), I'm getting an error:

GPG key '/usr/share/keyrings/ubuntu-fips-keyring.gpg' not found

If I do `sudo touch /usr/share/keyrings/ubuntu-fips-keyring.gpg`, this seems to work around the issue and I can enable it.

**Comment by powersj** [comment]
Right, none of the FIPS service work is enabled currently. This work is on-going.
