### ISSUE TITLE
attaching a ua apps contract token is too repetitive in output

### ISSUE THREAD

**Issue by mitechie** [CanonicalLtd/ubuntu-advantage-client#1311]
Enabling default service esm-apps
    Updating package lists
    ESM Apps enabled
    A reboot is required to complete install
    Enabling default service esm-infra
    Updating package lists
    ESM Infra enabled
    A reboot is required to complete install
    Enabling default service livepatch
    Installing canonical-livepatch snap
    Canonical livepatch enabled.
    This machine is now attached to 'UA Applications - Essential (Physical)'

Note the repeating "A reboot is required to complete install". 

Also note that the notices section doesn't have that where it might be the only place we need it in this attach scenario. 

    SERVICE       ENTITLED  STATUS    DESCRIPTION
    esm-infra     yes       enabled   UA Infra: Extended Security Maintenance (ESM)
    fips          yes       n/a       NIST-certified FIPS modules
    fips-updates  yes       n/a       Uncertified security updates to FIPS modules
    livepatch     yes       enabled   Canonical Livepatch service

    NOTICES
    Operation in progress: ua attach

If the reboot info showed in notices it might be enough and not needed during the "progress" section of output?

**Comment by orndorffgrant** [comment]
Tracking in SC-186
