### ISSUE TITLE
New livepatch status: kernel-upgrade-required

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#158]
There is a new livepatch status that should be covered in the motd. From https://github.com/CanonicalLtd/livepatch-client/commit/d7545d4df08940debab4651aa0e3cd39238343b9:

> "Dead Branch" Status
> 
> This patch adds a new "dead" status, for kernel versions that
> have been obsoleted due to an unpatchable CVE in a new release.
> The state is keyed off a special flag file that will be added
> to the final release of each obsolete kernel's livepatch
> tarball. When the file is present, the livepatch client will
> display its status as "kernel-upgrade-required."

**Comment by powersj** [comment]
We do not show detailed status of livepatch anymore, so closing this.
