### ISSUE TITLE
Move from cronjob to systemd timer

### ISSUE THREAD

**Issue by BryanQuigley** [CanonicalLtd/ubuntu-advantage-client#164]
Happy to do the work, but wanted to get a +1 to the idea first.

On the flip side, maybe we just shouldn't run at all on non-LTS releases..

**Comment by panlinux** [comment]
This code is about to get a big overhaul in the next week or two. The WIP branch is `python-ua-client`. Let's hold on this until that lands.

The only comment I have is that this must still work on trusty, which is not systemd based, but in general, a systemd timer is better than a cron job indeed.

**Comment by BryanQuigley** [comment]
Thanks!  Will hold off until that lands.

**Comment by powersj** [comment]
We no longer have any cron jobs with the new client, so I am closing this bug.
