### ISSUE TITLE
Complete manpage for new `ubuntu-advantage` tool

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#188]
The existing manpage has been updated partially for the Python-based tool, but still needs pushing over the finish line.

(One example of something that needs fixing: the return codes section.)

**Comment by OddBloke** [comment]
Oh, actually, looking at git history it's been partially updated for the new client; repurposing this issue.

**Comment by powersj** [comment]
Here is my review of the man page:

- Need to update it to include common criteria if we do in fact include it to the various lists of supported services and enable/disable commands
- Need to update the attach token URL
- The paragraphs for each service are spaced and titled very oddly. These need to be fixed
- The exit status list needs to be updated to either 0 or 1, I don't believe we use any other status code @blackboxsw can confirm
