### ISSUE TITLE
config: Add config subcommand to write /etc/ubuntu-advantage/uaclient.conf valuees (for cloud-init)

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#226]
Cloud-init may need to surface #cloud-config to the ubuntu-advantage config module to support setting /etc/ubuntu-advantage/uaclient.conf  contract_url settings to staging services.

This issue represents discussion about whether ua client should have a config subcommand accepting key/value pairs so it can write it's own config.

**Comment by powersj** [comment]
I am inclined to close this. I do not see large value in this one for the bulk of our users and instead see this as something we might use for testing only. In that case, a `sed` seems simpler than maintaining another subcommand.

Thoughts?
