### ISSUE TITLE
status as JSON

### ISSUE THREAD

**Issue by powersj** [CanonicalLtd/ubuntu-advantage-client#227]
We need to have a machine readable output of stuats.

`ua status --json` 

should produce valid JSON output

**Comment by OddBloke** [comment]
Does this have to be `--json`? Implementing it as `--format json` (which is how lxd and multipass implement output format selection) would leave the door open to adding more output formats without polluting our command-line flag namespace.

**Comment by blackboxsw** [comment]
+1 on that suggestion, will change that now. and I agree. We should align with other tooling
