### ISSUE TITLE
apt entitlements should consume additionalPackages directive if present.

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#230]
apt entitlements (fips, fips-updates, cis-audit, esm, cc) should consume 'directive': {'additionalPackages': []} if present and fallback on the current hardcoded list of entitlement package names if not present. This will allow the backend to steer package dependencies if they change.
for more info: see ua-contracts https://github.com/CanonicalLtd/ua-contracts/pull/191

**Comment by powersj** [comment]
@blackboxsw can you confirm this is done? I believe it is now.

For esm it was not relivant, however fips, fips-updates, cis-audit, and cc all seem to be using it.

**Comment by blackboxsw** [comment]
Closing this item as the additionalPackages directive it too simplistic for services like FIPS and FIPS with updates. In cc and cis-audit case there is one mandatory named additionalPackage which is required. But, in FIPS* ua client should only automatically install fips-initramfs and linux-fips.

**IF** the following packages are already installed, then install their fips pinned version and available ** <package-name>-hmac ** package if present.


Closing this issue as we will reopen when we define a path through ua-contracts to express required-packages, and optional/conditional-packages.
