### ISSUE TITLE
uaclient honor enableByDefault entitlement obligation from ua-contracts to auto-enable an entitlement

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#239]
For an entitlement (esm|livepatch) those entitlements should automatically be enabled after `ua attach` if the entitlement specifies obligations: enableByDefault: true. This true value means:
   if the system meets all affordances (constraints) then it *should* be enabled upon 'attach' instead of manually enabled after the fact.

      "obligations" : {
         "enableByDefault" : true
      },

**Comment by powersj** [comment]
fips and fips-updates should NEVER be automatically enabled. These are "destructive" to a system and we always want a user to specify or specifically turn it on and absolutely never have it enabled without the user saying so.

**Comment by OddBloke** [comment]
The contract server may have more information than we do about auto-enable (e.g. it may grow support for an organisation *enforcing* FIPS everywhere, and then automatically enabling it probably *would* be the right thing to do).

**Comment by OddBloke** [comment]
The original implementation of the cloud-init config module for the new client would disable auto-enable if it was given any list of modules to enable; we probably need something along the lines of `--no-auto-disable` to be able to do this.
