### ISSUE TITLE
Add package builds to CI

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#245]
I broke package builds on at least trusty in #233, which would have been good to catch before it was merged.

To that end, we should consider adding basic package builds to our Travis runs.

**Comment by powersj** [comment]
What is our mechanism or documented suggestion for building now that the `deb` Makefile target is gone? FYI the README still says use `make deb`

**Comment by OddBloke** [comment]
Regular Debian packaging commands (e.g. `dpkg-buildpackage`) will build the package for whatever release we happen to be running on. I don't know that we have a good way of running across every release we support; perhaps we could investigate performing the builds in Docker, as Travis has first class support?

**Comment by OddBloke** [comment]
I started looking at building cloud-init packages in Travis, and most of that knowledge will transfer over easily to this project. I'll submit something today.
