### ISSUE TITLE
secrets in 0644 files in /var/lib/ubuntu-advantage

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#254]
I noticed that all files in `/var/lib/ubuntu-advantage` are mode 0644, and the directory itself is 0755. Many of these files seem to contain secrets, like the password used to access the esm/fips repositories, livepatch token, and so on.

In the case of repository access, we store these secrets in a 0600 file in `/etc/apt/auth.conf.d/`, so we do care about it. But if it's world-readable elsewhere, that point is moot.

I understand that the ua spec calls for some commands to work as a regular user, while others need root. For example, `ua status` should work as a regular user. But it tries to read a file that contains secrets:
```
ubuntu@trusty-ua:~$ ua status
Account: andreas.hasenack@canonical.com
Subscription: andreas.hasenack@canonical.com
Valid until: 0001-01-01
Technical support level: not included

cis-audit     none             inactive
cc            entitled         n/a
esm           entitled         inactive
fips          entitled         n/a
fips-updates  entitled         n/a
livepatch     entitled         inactive

Enable entitlements with `ua enable <service>`

ubuntu@trusty-ua:~$ sudo chmod 0600 /var/lib/ubuntu-advantage/*
ubuntu@trusty-ua:~$ ua status
Traceback (most recent call last):
  File "/usr/bin/ua", line 9, in <module>
    load_entry_point('ubuntu-advantage-tools==18.1', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 374, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 292, in action_status
    if not cfg.is_attached:
  File "/usr/lib/python3/dist-packages/uaclient/config.py", line 139, in is_attached
    return bool(self.machine_token)   # machine_token is removed on detach
  File "/usr/lib/python3/dist-packages/uaclient/config.py", line 145, in machine_token
    self._machine_token = self.read_cache('machine-token')
  File "/usr/lib/python3/dist-packages/uaclient/config.py", line 172, in read_cache
    content = util.load_file(cache_path)
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 96, in load_file
    with open(filename, 'rb') as stream:
PermissionError: [Errno 13] Permission denied: '/var/lib/ubuntu-advantage/machine-token.json'
```
If we don't have a clear solution for this, maybe at first we need to make `ua` only runnable by root?

**Comment by cpaelzer** [comment]
There still are things in the world readable `-rw-r--r--` form at /var/lib/ubuntu-advantage/
It seems most moved to the private subdir, but are we sure that 
```
{"machineToken": "mAg...
"accountInfo": {"id": "aAM...
"aptKey": "1...
...
```
are not sensitive at all?
In most companies such subscriptions are usually handled with very limited access.
Posting here to reconsider if we'd want to move "more" (or since we only run as root just all) into the private subdir.

**Comment by OddBloke** [comment]
I'm not in a position to comment about whether these pieces of information are sensitive, but I will note that we explicitly _do_ support running `ua status` as a non-root user.

**Comment by cpaelzer** [comment]
Interesting @OddBloke , what is the concept for the authentication then for the non-root users to be allowed to:
a) see
b) control
ua configuration?

IMHO a random user on a system with UA will at most be allowed to barely see that it is running and what is enabled. But even the account name it is on would be sensitive I'd think. Even more so all that is discussed for a `status --verbose`.

And for (b) obviously you'd then want some authentication, but I'm not sure which one if "access to root" isn't the way. Is there and pointer about the design/intention in that regard?

**Comment by OddBloke** [comment]
@cpaelzer It maybe makes sense to open a new issue for specific issues/concerns you have? I think this issue is too general/too implementation specific for us to reopen, so any conversation here may well be lost/missed in future.

**Comment by cpaelzer** [comment]
@OddBloke this now is in #494
