### ISSUE TITLE
Clean up dev directory

### ISSUE THREAD

**Issue by powersj** [CanonicalLtd/ubuntu-advantage-client#255]
Now that we have a staging service that is live we should be using that for development. Can we please clean out any and all scripts that are no longer used from the directory?

Mark for possible removal:

- contracts-controller.patch
- contracts-go.patch
- contracts-implemented-controller.patch
- contracts-schema.patch
- demo-contract-service
- entitlement-creds.json (?)
- install-contracts-server
- pkg-deps.json
- run-uaclient
- runserver.sh
- uaclient

That would leave the following, which are there to help with development and packaging:

- bddeb
- changelog.in
- constraints-bionic.txt
- constraints-trusty.txt
- constraints-xenial.txt
- control.in
- make-tarball
- pkg-deps.json
- read-dependencies
- README.txt

Final changes:

- I would like README.txt renamed to README.md
- If we do not remove entitlement-creds.json, then we should update it for our package and not re-use cloud-init data as-is.

**Comment by OddBloke** [comment]
For an ideal development environment, we should be able to spin up a server locally for testing. As this week has taught us, relying on a staging service is a good way of stalling out development for hours (or days) at a time. It also means that we can't develop features against what's in production if the staging environment is ahead of production and, conversely, means that we have to wait for changes to get all the way to staging before we can start developing against them.

(Also: I'm not saying we shouldn't do all of the things listed in the issue, but I did want to dispute that we should be using a staging service for development long-term. :-) )

**Comment by powersj** [comment]
After thinking about this some more I do agree that having a way to demo the client would still be good to have. I have submitted a merge above that splits the dev directory into two: tools for scripts, tests, and building help and demo for well demo stuff :)

After the first release we should get the demo directory working again
