### ISSUE TITLE
Colors do not work with other themes

### ISSUE THREAD

**Issue by powersj** [CanonicalLtd/ubuntu-advantage-client#259]
I use Solarized light/dark themes on my terminal and the result is that the `ua status` output looks terrible or difficult to read.

**Comment by OddBloke** [comment]
Why was this closed?

**Comment by powersj** [comment]
I closed it since I played with my own theme and it seemed to work with others.

Are you seeing it as well?

**Comment by OddBloke** [comment]
I'm not, just wanted to make sure that we captured the reason we closed this in case other people _do_ hit it and find this issue. :-)
