### ISSUE TITLE
Daily build on Trusty failing

### ISSUE THREAD

**Issue by powersj** [CanonicalLtd/ubuntu-advantage-client#264]
Four test failures all TypeErrors with the function signatures

https://launchpadlibrarian.net/417565519/buildlog_ubuntu-trusty-amd64.ubuntu-advantage-tools_19.1-0ubuntu1~364~git.5c3dd3a~ubuntu14.04.1_BUILDING.txt.gz

**Comment by panlinux** [comment]
5ea5c87d8afa60e5a7e732c431e415222550fcd5 works
6b12157002e6b0bac5477a22370d35710d10f0ff onwards breaks

**Comment by powersj** [comment]
Failing tests include:

- `test_can_enable_true_on_entitlement_inactive`
E               TypeError: test_can_enable_true_on_entitlement_inactive() missing 1 required positional argument: 'fips_entitlement'

- `test_enable_configures_apt_sources_and_auth_files`
E               TypeError: test_enable_configures_apt_sources_and_auth_files() missing 1 required positional argument: 'fips_entitlement'

- `test_enable_errors_on_repo_pin_but_invalid_origin`
E               TypeError: test_enable_errors_on_repo_pin_but_invalid_origin() missing 2 required positional arguments: 'caplog_text' and 'fips_entitlement'

- `test_disable_returns_false_and_removes_apt_config_on_force`
E               TypeError: test_disable_returns_false_and_removes_apt_config_on_force() missing 1 required positional argument: 'fips_entitlement'

**Comment by powersj** [comment]
It looks like all the tests that use the fips_entitlement fixture are not picking it up.
