### ISSUE TITLE
/etc/update-motd.d/99-esm hardcodes precise, expects old ua tool

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#276]
We may have a task somewhere to handle motd, but at the moment at least the `/etc/update-motd.d/99-esm` file is still the old one from the bash version of ua and hardcodes precise.

Not only that, it uses syntax from the old ua tool: `if ubuntu-advantage is-esm-enabled; then`

Which fails:
```
root@trusty-ua:~# /etc/update-motd.d/99-esm
usage: ubuntu-advantage [command] [flags]
ubuntu-advantage: error: argument : invalid choice: 'is-esm-enabled' (choose from 'status', 'attach', 'detach', 'enable', 'disable', 'version')
This Ubuntu 14.04.6 LTS system is past its End of Life, and is no longer
receiving security updates.  To protect the integrity of this system, it’s
critical that you enable Extended Security Maintenance updates:
 * https://www.ubuntu.com/esm
```

**Comment by panlinux** [comment]
This file is not part of the new client, so it should be removed in postinst by a maintainer script.

**Comment by panlinux** [comment]
Files and directories that can be removed:
- `/etc/update-motd.d/99-esm`: we are not doing that here anymore?
- `/etc/update-motd.d/80-livepatch`: we are not doing that here anyore?
- `/var/cache/ubuntu-advantage-tools`: was used by the livepatch motd, present in bionic and later
- `/etc/cron.daily/ubuntu-advantage-tools`: was used to generate a `ua status` output daily, to be consumed by the MOTD scripts

**Comment by powersj** [comment]
marking closed
