### ISSUE TITLE
lintian: ancient-standards-version

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#279]
W: ubuntu-advantage-tools source: ancient-standards-version 3.9.6 (released 2014-09-17) (current is 4.3.0)

**Comment by powersj** [comment]
Is this as simple as updating the field and then verifying it can build still without any other new warnings or errors? What about when we build for trusty, will it have issues with the newer version?

**Comment by cpaelzer** [comment]
In general it is a list of recommended behaviors that you are supposed to follow see [upgrading checklist](https://www.debian.org/doc/debian-policy/upgrading-checklist.html).
For backports that can be tricky, one one hand the trusty builds will call out some versions as "too new" which isn't a problem in itself.
But if you have added calls to tools which are not supported you will get problems. Fortunately standards is mostly a guide how to behave and only rarely command options (that would be more [compat level](https://manpages.debian.org/testing/debhelper/debhelper.7.en.html)).

Therefore generally for a case like this what should be done is evaluating the upgrade checklist one by one. Most likely you will only hit things that are no backport issue, change them and eventually set the new standards version. If you encounter something that you think will be a backport issue that needs to be discussed individually.
