### ISSUE TITLE
livepatch: trusty non-hwe kernels (< 4.4) not supported

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#288]
ua client should report status 'n/a' instead of 'inactive'

if uaclient tries enabling livepatch on trusty's 3.3 kernels:

uaclient.util.ProcessExecutionError: Failed running command 'snap install canonical-livepatch' [exit(1)]. Message: b'error: system does not fully support snapd: you need to reboot into a 4.4\n       kernel to start using snapd\n'

**Comment by powersj** [comment]
This still shows inactive on trusty
