### ISSUE TITLE
libapt-pkg-dev missing from deps?

### ISSUE THREAD

**Issue by powersj** [CanonicalLtd/ubuntu-advantage-client#291]
I had to install this to build the package correctly on my Bionic system. Is this something we need to add somewhere? It seems our package is building fine on launchpad, but was wondering how I was missing this, yet Launchpad is building fine?

Steps to reproduce:
`make build`

**Comment by panlinux** [comment]
It is in `debian/control`:
https://github.com/CanonicalLtd/ubuntu-advantage-client/blob/master/debian/control#L8
