### ISSUE TITLE
livepatch: retry snap install operation on intermittent errors

### ISSUE THREAD

**Issue by cpaelzer** [CanonicalLtd/ubuntu-advantage-client#308]
Hi,
in a discussion about #299 it came up that long term (i.e. not for the release now) we might want to wrap some actions e.g. those that are network dependent or others that are just known to potentially be flaky for whatever reason into retry actions.
That should not mean we should write and allow flaky code ourselves, but only that e.g. "snap install" which can fail due to network issues but often works in a retry then could provide a better experience if retried transparently.

Update:
We should be able to surface an optional retries param to util.subp to cope with most use cases.

**Comment by blackboxsw** [comment]
Thanks Christian for this issue. I'm changing this to directly something specific that is actionable in uaclient code. For this particular issue.

Changing the title "Retry some activities that are known to potentially be flaky" to  'Retry "snap install" and apt update on intermittent errors'.

**Comment by OddBloke** [comment]
On Mon, May 06, 2019 at 11:40:35AM -0700, Chad Smith wrote:
> Changing the title "Retry some activities that are known to
> potentially be flaky" to  'Retry "snap install" and apt update on
> intermittent errors'. 

I would suggest that those are two distinct issues; we don't have a
shared code path for these two commands.

**Comment by blackboxsw** [comment]
Created separate apt retries issue #496   This issue will address only livepatch snap retries
