### ISSUE TITLE
Be consistent when using Ubuntu release names

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#314]
We should probably capitalize the Ubuntu series name:

```
$ sudo ua enable fips
FIPS is not available for Ubuntu trusty.
```
We could have a nice mapping between code names ("trusty") and visible names, something like:
`trusty -> Ubuntu 14.04 LTS ("trusty")`

`/etc/lsb-release` has a description field. For trusty, for example, it is `DISTRIB_DESCRIPTION="Ubuntu 14.04.6 LTS"`

**Comment by OddBloke** [comment]
The distro-info-data package installs `/usr/share/distro-info/ubuntu.csv` which contains the necessary information to produce a friendlier name; we would normally do "Ubuntu 14.04 LTS (Trusty Tahr)" on CPC, which is `"Ubuntu {version} ({codename})".format(**row)` from `ubuntu.csv`.

(I think including the codename would be preferable, as some people do know Ubuntu releases by them; `/etc/lsb-release` doesn't have the full codename whereas `ubuntu.csv` does.)

**Comment by OddBloke** [comment]
Here are a few options:

`PRETTY_NAME` from `/etc/os-release`:

```
PRETTY_NAME="Ubuntu 14.04.6 LTS"
PRETTY_NAME="Ubuntu 16.04.6 LTS"
PRETTY_NAME="Ubuntu 18.04.2 LTS"
PRETTY_NAME="Ubuntu 19.04"
PRETTY_NAME="Ubuntu Eoan Ermine (development branch)"
```

`VERSION` from `/etc/os-release`:

```
VERSION="14.04.6 LTS, Trusty Tahr"
VERSION="16.04.6 LTS (Xenial Xerus)"
VERSION="18.04.2 LTS (Bionic Beaver)"
VERSION="19.04 (Disco Dingo)"
VERSION="19.10 (Eoan Ermine)"
```

`lsb_release -sd`:

```
Ubuntu 14.04.6 LTS
Ubuntu 16.04.6 LTS
Ubuntu 18.04.2 LTS
Ubuntu 19.04
Ubuntu Eoan Ermine (development branch)
```

**Comment by OddBloke** [comment]
Of these, I think I like the middle one (`VERSION` from `/etc/os-release`) the most.

(The inconsistency on trusty is annoying, but we can either live with that or fix it up explicitly in our display code.)

**Comment by OddBloke** [comment]
Oh, another option *is* to use `distro-info-data`; it's only in images from xenial onwards (at which point it is in minimal, so we can rely on it pretty broadly) but we can special-case trusty. This would probably be my preferred option as we can build the exact description we want more easily. This is the available data (for the relevant releases):

```
version,codename,series,created,release,eol,eol-server,eol-esm
14.04 LTS,Trusty Tahr,trusty,2013-10-17,2014-04-17,2019-04-25,2019-04-25,2022-04-25
16.04 LTS,Xenial Xerus,xenial,2015-10-22,2016-04-21,2021-04-21,2021-04-21,2024-04-21
18.04 LTS,Bionic Beaver,bionic,2017-10-19,2018-04-26,2023-04-26,2023-04-26,2028-04-26
19.04,Disco Dingo,disco,2018-10-18,2019-04-18,2020-01-18
19.10,Eoan Ermine,eoan,2019-04-18,2019-10-17,2020-07-17
```

**Comment by blackboxsw** [comment]
I vote VERSION, and I'd prefer not to have a package dependency on distro-info if it can be avoided.

**Comment by OddBloke** [comment]
@blackboxsw What is your concern with depending on `distro-info-data`? Except for trusty, it's already in the minimal seed so will be present on every Ubuntu system whether or not we depend on it.

(And on trusty I think we can safely hardcode the string "14.04 LTS (Trusty Tahr)" or whatever we decide, because we know that isn't going to change.)

**Comment by powersj** [comment]
The formal, correct way to represent a release is `Ubuntu YY.MM [LTS] (Adjective Animal)`. As such that would be the `VERSION` field from `/etc/os-release`. We already parse that data throughout the code so I would suggest we continue to do so. As stated by others, we can fix up Trusty.

**Comment by OddBloke** [comment]
Cool, I'll go with `VERSION` from `/etc/os-release`. I think excluding the point release would be ideal, so I'll also see if I can do that (it should just be `s/\.\d LTS/ LTS/` so I don't think it'll be a huge challenge).

(I'd like to exclude the point release because I think saying we don't support an entitlement on, say, 18.04.2 will prompt the question of which version of 18.04 we _will_ support it in. That's not how we use point releases at all, so I'd like to avoid them if possible.)

**Comment by blackboxsw** [comment]
per !package dependency on distro-info. no concern other than another dependency on something that is very similar to what is present already in /etc/os-release.  Just a desireb to keep package dependency lines smaller and legible.
