### ISSUE TITLE
cis-audit shows inactive instead of n/a on disco

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#332]
Hi,

on disco I get this after attaching:
```
Account: andreas.hasenack@canonical.com
Subscription: andreas.hasenack@canonical.com
Valid until: 0001-01-01
Technical support level: not included

cc            entitled         n/a
cis-audit     none             inactive
esm           entitled         n/a
fips          entitled         n/a
fips-updates  none             n/a
livepatch     entitled         n/a
```

I was expecting `cis-audit` to be shown as `n/a` as well, unless it's supposed to be available for non-LTS releases.

A grep for `cis-audit` in `/var/lib/ubuntu-advantage` returns no hits, so it looks like the server is telling us nothing about it, and the client is falling through some assumption.

**Comment by blackboxsw** [comment]
Current tip of uaclient reports cis-audit as unentitled (none) and n/a
Commitish b154cbb201a4ea4a2e7c7aa8bfa564683fccd3b8 per feature/ua-contracts-absent-entitlement fixed this
