### ISSUE TITLE
Only root sees esm enabled

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#339]
I can't say if this is realted to commit 476598c.
After I enable esm, I see this behavior:
```
ubuntu@trusty-ua:~$ sudo ua status|grep esm
esm           entitled         active

ubuntu@trusty-ua:~$ ua status|grep esm
esm           entitled         inactive
```

Same with `apt-cache policy`:
```
ubuntu@trusty-ua:~$ apt-cache policy | grep esm
-32768 https://esm.staging.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
     origin esm.staging.ubuntu.com

ubuntu@trusty-ua:~$ sudo apt-cache policy | grep esm
 500 https://esm.staging.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
     origin esm.staging.ubuntu.com
```

**Comment by panlinux** [comment]
I don't see how `ua` would interfere with `apt-cache policy` not working. I'll troubleshoot more tomorrow

**Comment by panlinux** [comment]
If I make `/etc/apt/auth.conf.d/90ubuntu-advantage` mode `0644`, then both `ua status` and `apt-cache policy` will say esm is enabled (and pinning 500 instead of -32768 in the case of `apt-cache`).

I can't tell right now if this is new behavior, or if it was like this since the beginning.

**Comment by blackboxsw** [comment]
This is new behavior because apt not magically checks auth perms to a repo to set this magic pin

**Comment by blackboxsw** [comment]
UAClient could capture when an entitlement was enabled to help out the non-root user case, But I'm wondering if there is another besides checking apt-cache policy  for the magic pin for non-root user. Maybe Julian has thoughts here.

**Comment by julian-klode** [comment]
I mean, you could just write individual files per entitlement and then check for their presence. This does not help apt as user though, as it will still see ESM being disabled because apt can't read the file.

If this is a severe limitation we want to get rid of, we have to disable writing Packages-Require-Authorization to the Release file and manually pin the ESM repo down with "Pin-Priority: never" (and ua needs a Depends apt (>= version with that feature).

**Comment by panlinux** [comment]
This is somewhat new behavior. In the old bash ua client, we used to write sources.list.d files with creds in there, mode 0644, exactly because making them 0600 would break apt-cache policy. That's when we were directed at auth.conf, which *can* be made 0600 and apt-cache policy would still work, and it did.

**Comment by panlinux** [comment]
@julian-klode in issue #275, we had to make sure we would produce an auth.conf.d/ file carefully crafted:
 - more specific entries at the top
 - one entry with just the esm hostname, ending with a slash (/)

How does that work with the idea of splitting one such file out into multiple files? Do we need to keep these rules and use numbered filenames to keep the order?

For example:
auth.conf.d/ua:
```
machine esm.staging.ubuntu.com/otherservice/ login bearer password another-password
machine esm.staging.ubuntu.com/ login bearer password a-password
```

would become:
auth.conf.d/01-ua-other-service:
```
machine esm.staging.ubuntu.com/otherservice/ login bearer password another-password
```
auth.conf.d/02-ua:
```
machine esm.staging.ubuntu.com/ login bearer password a-password
```
Or is the solution from issue #275 thrown out the window if we split auth.conf files, one for each service?
