### ISSUE TITLE
Livepatch entitlement uses `which snap` to determine if snapd is installed

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#356]
`snapd` is not the only package to provide a snap command (at least in trusty):

```
$ apt-file search -x bin/snap$
snap: /usr/bin/snap
snapd: /usr/bin/snap
```

(This is low priority to fix, but is nonetheless a possible failure case.)

**Comment by powersj** [comment]
We could do something like: `dpkg-query --show --showformat='${db:Status-Status}\n' 'snapd'` and verify that the output is 'installed'.

Thoughts?

**Comment by OddBloke** [comment]
I think checking the exit code of `dpkg-query --show snapd` would be sufficient:

```
$ dpkg-query --show snapd; echo $?
snapd	2.38+19.04
0
% dpkg-query --show nope; echo $?
dpkg-query: no packages found matching nope
1
```

**Comment by panlinux** [comment]
Hmm, old ubuntu-advantage-tools was using dpkg-query to determine if something wasn't installed, but we had to change it. Unfortunately commit 057f9c033319b55affd78c6fcb24a56b36a85773 doesn't say why, and I don't remember the reason either. Maybe in precise it worked differently? I just tried in trusty, and it works just like you said.
