### ISSUE TITLE
test_cis should include a test that `apt-transport-https` and `ca-certificates` are installed if necessary

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#359]
Currently we only test one case (which, until #357 is fixed, is the case of the system on which the tests are running).

(We should also consider whether we can drop and/or consolidate the "enable" testing for the RepoEntitlement subclasses.)

**Comment by powersj** [comment]
CIS is a 19.7 item, so moving milestone.
