### ISSUE TITLE
Enable ESM and Livepatch after logging in

### ISSUE THREAD

**Issue by powersj** [CanonicalLtd/ubuntu-advantage-client#360]
By default when I attach, ESM and livepatch should be enabled if possible.

- ESM should have no problems to enable
- Livepatch should only be enabled if possible. So on Trusty you would enable if the user was on the HWE kernel, but not if they were on the shipping kernel.

**Comment by powersj** [comment]
@blackboxsw We should file a bug with the contracts to tell us what to enable or disable by default.

**Comment by OddBloke** [comment]
Is this effectively a duplicate of #239?

**Comment by OddBloke** [comment]
Closing in favour of #239.
