### ISSUE TITLE
fips is n/a, but fips-updates is just "inactive"?

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#363]
These are the fips entitlements nn my bionic system, registered with staging (but the same happened with production):
```
root@nsnx:~# ua status|grep fips
fips          entitled         n/a
fips-updates  none             inactive
```
So I'm entitled to fips, but it's not available for bionic:
```
root@nsnx:~# ua enable fips
FIPS is not available for Ubuntu bionic.
root@nsnx:~# 
```
How come `fips-updates` just be `inactive` then? Shouldn't it be `n/a` as well? Is this fallout from having disabled fips-updates on the server for testing?

**Comment by blackboxsw** [comment]
This is blocked by https://github.com/CanonicalLtd/ua-contracts/issues/256  above ^

**Comment by OddBloke** [comment]
Do we need to consider handling this type of situation generically, perhaps by modifying the way we do defaulting?

(FWIW, I don't think the generic solution need be a blocker; fixing the issue Chad pointed at is sufficient to unblock, I think?)

**Comment by blackboxsw** [comment]
We had a discussion with Uros and Martin and David there is upcoming work that will omit access details (affordances) any unentitled service. As a result, uaclient will not know anything about the support matrix of 'fips' if fips is unentitled.  Without specific affordances, uaclient will only report that  fips/cc/fips-updates are 'n/a'.   If the service is entitled, ua-contracts will provide uaclient with affordances and then uaclient can report :
 - *n/a*: if the service is entitled, but *does not* meet all affordances
 - *inactive*: if the service is entitled, meets all affordances, and *is  not* configured
 -  *active*: if service is entitled, meets all affordances, and *is* configured

For an unentitled service uaclient will report 
Name:                                 contractstatus    operational status
*<entitlement_name>*        *unentitled*         *n/a*

**Comment by OddBloke** [comment]
@blackboxsw I think we can close this out in favour of #442, what do you think?

**Comment by blackboxsw** [comment]
Agreed. copying expected uaclient behavior comment  to #442 as well
