### ISSUE TITLE
Support disabling auto-enablement of entitlements on attach

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#366]
Once #360 is fully implemented, we will want a way to disable the automatic enablement of entitlements at `ua attach` time. This will allow users who know precisely what entitlements they want enabled/disabled to only enable those they want enabled.

**Comment by blackboxsw** [comment]
From ua-contracts responses in machine-access-<name>.json, client needs to check obligations:enableByDefault (bool) and enable the service if can_enable() == True && obligations.enableByDefault
Here are the examples from ua-contracts responses:


for file in /var/lib/ubuntu-advantage/private/machine-access-*;  do echo $file; sudo cat $file | jq '.entitlement.obligations'; done
/var/lib/ubuntu-advantage/private/machine-access-cc.json
{
  "enableByDefault": false
}
/var/lib/ubuntu-advantage/private/machine-access-esm.json
{
  "enableByDefault": true
}
/var/lib/ubuntu-advantage/private/machine-access-fips.json
{
  "enableByDefault": false
}
/var/lib/ubuntu-advantage/private/machine-access-fips-updates.json
{
  "enableByDefault": false
}
/var/lib/ubuntu-advantage/private/machine-access-livepatch.json
{
  "enableByDefault": true
}
/var/lib/ubuntu-advantage/private/machine-access-support.json
{
  "enableByDefault": false
}

**Comment by powersj** [comment]
Is this proposing something like: `ua attach --no-auto` that would skip auto-enablement?

**Comment by OddBloke** [comment]
Yes, exactly.
