### ISSUE TITLE
If $suite-updates is not configured at enable time, we should still write out a commented example

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#369]
In #343, we ensured that we won't enable `$suite-updates` for repo entitlements that are enabled on systems that don't have `$suite-updates` configured for their regular apt sources.

A nice enhancement to this would be to write out the lines we _would_ have written out, but commented; this makes it easier for people to manually enable `$suite-updates` at a later date.

(I think @panlinux suggested this in a call yesterday, so I'm capturing it here.)

**Comment by powersj** [comment]
+1

**Comment by OddBloke** [comment]
This is still applicable, even after #573 lands.

**Comment by OddBloke** [comment]
Taking #396 and #369 together because they are likely to have some overlap.
