### ISSUE TITLE
FIPSCommonEntitlement.disable() always returns False

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#371]
Even when force is passed and it successfully performs all the force actions.

(I'm not sure if this is a bug, techdebt or intentional; I noticed it when reading the code. I've tagged it as both for now.)

**Comment by powersj** [comment]
FIPS and FIPS Updates are not possible to disable as once you have installed the packages it is too hard to go back.

Maybe this is possible improvement for the UX of the CLI?

**Comment by OddBloke** [comment]
We have code which will (attempt to) disable FIPS and FIPS Updates if you pass in the `force` parameter at https://github.com/CanonicalLtd/ubuntu-advantage-client/blob/master/uaclient/entitlements/fips.py#L19. It looks to me like this is only ever used when we've failed to install the packages and are attempting cleanup (at https://github.com/CanonicalLtd/ubuntu-advantage-client/blob/master/uaclient/entitlements/repo.py#L106).

This feels like a distinct operation to `disable` to me (perhaps `cleanup`?), because the FIPS entitlements should always fail to disable. Indeed, even if `force` is passed in, we will still emit a message saying you can't disable FIPS despite just having attempted to do so.

**Comment by panlinux** [comment]
Correct, that (partial?) removal was made to cope with aborted installs. We have no guidance from the fips team on how to disable it.

**Comment by OddBloke** [comment]
OK, I think it's clear this isn't a bug, so I'll leave this just tagged as tech debt.

**Comment by OddBloke** [comment]
This will be fixed once #607 lands, so assigning myself so no-one else ends up digging in to it.
