### ISSUE TITLE
Make apt hook more resilient

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#374]
We have had two critical bugs in the apt-hook recently that had a high impact on disco:
- failed to produce images
- once images were produced, the server subiquity installer failed

We should:
- figure out a better way of testing this, before it lands
- make it so that even if it crashes, it won't take the whole apt transaction with it. This is just for an advertisement text anyway

**Comment by OddBloke** [comment]
@panlinux I don't know how to reproduce this; is this still an issue?

**Comment by powersj** [comment]
@panlinux and @julian-klode is there a way for us to test this? If not I want to document whatever testing we could do and close this.

**Comment by julian-klode** [comment]
Well I don't have anything useful for testing. The crash was a race condition. There certainly are tests we could write with some `chroot`-like alternate roots (w/ var/lib/apt/lists, etc/apt, and var/lib/dpkg/status) and then run the hook on those and verify the output; but I haven't written any so far. It certainly would not have discovered the issue.

We can obviously make it not fail apt by adding `|| true` to the options, but I'm not sure if failing but continuing is a worthwhile goal - imagine it being broken on the final image, and nobody noticed.

**Comment by powersj** [comment]
I don't see a way forward, so I am closing this for now.
