### ISSUE TITLE
`ua` doesn't detect repo entitlements as active until an apt update has happened

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#377]
To set up this reproducer, I launched a lxd container, enabled proposed and the daily PPA, and installed ubuntu-advantage-tools 19.4\~406\~git.fb8f7cd. I then copied the staging configuration from the repo to `conf`.

```
# UA_CONFIG_FILE=conf ua status
This machine is not attached to a UA subscription.
See `ua attach` or https://ubuntu.com/advantage

# UA_CONFIG_FILE=conf ua attach
Email: daniel.watkins@canonical.com
Password: 
Second-factor auth: <snip>
This machine is now attached to 'daniel.watkins@canonical.com'.

Account: daniel.watkins@canonical.com
Subscription: daniel.watkins@canonical.com
Valid until: 0001-01-01
Technical support level: not included

cc            entitled         n/a
cis-audit     none             inactive
esm           entitled         inactive
fips          entitled         n/a
fips-updates  entitled         n/a
livepatch     entitled         n/a

Enable entitlements with `ua enable <service>`

# UA_CONFIG_FILE=conf ua enable esm
Extended Security Maintenance enabled.
# UA_CONFIG_FILE=conf ua status
Account: daniel.watkins@canonical.com
Subscription: daniel.watkins@canonical.com
Valid until: 0001-01-01
Technical support level: not included

cc            entitled         n/a
cis-audit     none             inactive
esm           entitled         inactive
fips          entitled         n/a
fips-updates  entitled         n/a
livepatch     entitled         n/a

Enable entitlements with `ua enable <service>`
```

At this point, ESM should be displayed as `active`, but it isn't until I do an `apt update`:

```
# apt update
<snip>
Fetched 66.4 kB in 2s (26.1 kB/s)
Reading package lists... Done

# UA_CONFIG_FILE=conf ua status
Account: daniel.watkins@canonical.com
Subscription: daniel.watkins@canonical.com
Valid until: 0001-01-01
Technical support level: not included

cc            entitled         n/a
cis-audit     none             inactive
esm           entitled         active
fips          entitled         n/a
fips-updates  entitled         n/a
livepatch     entitled         n/a

Enable entitlements with `ua enable <service>`
```

**Comment by OddBloke** [comment]
This also means that the following doesn't work:

```
$ ua attach
...
$ ua enable esm
...
$ ua disable esm
Extended Security Maintenance is not currently enabled.
See `ua status`
```

Even though a user has run `ua disable esm`, they still have ESM enabled.

**Comment by blackboxsw** [comment]
This case looks like it'll only affect esm, because it is the only entitlement that does not auto-install packages from the repo on 'enable'. 

That said, if we want to avoid the cost of an apt-get update round trip during the enable of esm. We could leverage the non-root [ua status branch](https://github.com/CanonicalLtd/ubuntu-advantage-client/pull/350) which adds a localEnabled: True flag upon enable operation. This would save us a round trip with apt update.

**Comment by OddBloke** [comment]
I think that doing an `update` during ESM enable would be reasonable. I would expect most users to want to install the newly-available packages immediately after they enable ESM, so they won't actually spend any more time on their whole "enable ESM and install updates" task if we do it during `enable`.
