### ISSUE TITLE
`remove_auth_apt_repo`'s should remove everything it's given

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#395]
Currently it will silently not remove a key fingerprint if given. Per #394, this isn't a problem ATM, but we should fix it (if we don't remove it as part of #394).

**Comment by blackboxsw** [comment]
We've dropped the fingerprint reference by uaclient per commitish e12aab8e4d0102fb4f868a02624d89a7a6730868 OddBloke/fingerprint PR. So this issue is a non-issue now.
