### ISSUE TITLE
Write tooling to support testing natively in Ubuntu releases

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#397]
Running on disco, I've hit several issues when trying to run our tox targets for older Ubuntu releases because the versions of some of our dependencies simply aren't compatible with Python 3.7.

We should work out some tooling to make it easier for me to run tests in all of our target Ubuntu releases so I'm not reliant on just Travis for that testing. (Also, Travis isn't actually using our target Ubuntu releases, it just installs Python 3.x in to whichever release they're using, so we still have a gap even when relying on Travis).

**Comment by OddBloke** [comment]
(Also, we're already pinned at an incorrect pytest version for trusty due to compatibility issues.)

**Comment by powersj** [comment]
Travis is now running tests, packages builds per release, and now has some initial integration tests. I think we can close this and continue to add new features and releases as we come across them.
