### ISSUE TITLE
Reconcile the trusty constraints with trusty's versions

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#398]
Currently, `tools/constraints-trusty.txt` pins pytest to a higher version (2.6.2) than is present in trusty (2.5.1), so that we can run those tests on bionic.

In #382, I would have introduced a trusty-build-breaking change (if I hadn't happened to build a trusty package for testing), because the version of py in trusty doesn't have a method that I used in one of my tests. When attempting to pin to the version of py in `constraints-trusty.txt`, I ran in to problems: pytest 2.6.2 depends on a newer version of py (1.4.24) than the version in trusty (1.4.20), and 1.4.24 _does_ contain the methods that the trusty version doesn't.

Given the current newer-than-trusty pinning situation, there's no way to catch these issues, so I propose reconciling `constraints-trusty.txt` with the versions actually in trusty so that at least Travis can catch such things.

**Comment by powersj** [comment]
This amounts to tox not being the correct solution for our testing anymore. Short term, we can change the constraints back to trusty, but long term we need testing that:

- builds in an actual release environment (e.g. a container)
- pulls in the distro packages, not from pypi which currently do and is possible that there are differences there
- runs all unit tests
- runs all lint tests
- builds the package

**Comment by powersj** [comment]
Travis won't even be able to do all of the above as they only have environments for Trusty and Xenial. Bionic is on the radar, but not movement on it yet.

**Comment by OddBloke** [comment]
So I just attempted this, and to clarify the problem on bionic: the trusty version of pytest is incompatible with Python 3.6 AST. So even a short-term solution for this problem will require resolving that.
