### ISSUE TITLE
refresh/enable: client should expedite refresh calls to cut down on clock time while enabling an entitlement

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#399]
Currently ua enable calls the client's refresh operation which talks to 6 different routes on the ua-contract backend service to refresh all tokens/service creds. This takes a total of 6 seconds when enabling any entitlement from systems that may not have responsive access to ua-contracts service endpoint.

We need to think about avoiding blocking serialization of these calls to cut down on the total wall time while client collects this information to make the user experience on the CLI a bit better during enable.

**Comment by powersj** [comment]
I don't expect us to serialize this until the number of services drastically increases. The client is not something we expect users to run constantly like `ls`. The time is acceptable for now and I would rather us go after other bugs. Closing for now.
