### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#401]
We should do the appropriate gettext things in the Python code and packaging to allow ubuntu-advantage-client to be translated in to other languages.

(#383 has some of this, for the apt hook, but we should ensure the whole client is i18n'd.)

**Comment by cpaelzer** [comment]
Phrases that are hard to get right in English being translated, I'm already loving this :-)
@OddBloke - Feel free to ping me if you have a set of templates and you want German to be filled with an initial set of translations.

**Comment by powersj** [comment]
Not in plan anytime soon. Closing.
