### ISSUE TITLE
Install packaged gpg keys for cc, fips and fips-updates instead of using aptKey directive from ua-contracts service

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#404]
Currentlly uaclient looks at contract service response for an aptKey directive. If present, uaclient ignores the packaged gpg key ring for any apt-based service.

Per security team suggestion it may be better to just use our packaged keys instead of relying on the external response from ua-contracts service.

The code to look at is entitlements/repo.py:enable which has a mutual exclusion if aptKey is present:
```
        ppa_fingerprint = directives.get('aptKey')
        if ppa_fingerprint:
            keyring_file = None
        else:
            keyring_file = os.path.join(apt.KEYRINGS_DIR, self.repo_key_file)
```

**Comment by powersj** [comment]
In my mind a fix for this would involve:

- remove calls to apt-key (not considered stable interface and not something we should be using)
- ship the correct keys

However, we need to have a discussion about how we change keys. Using the entitlements would be one way to rotate keys.
