### ISSUE TITLE
Only attempt to enable enableByDefault entitlements if they are applicable to the current system

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#411]
Entitlements can have the `enableByDefault` obligation, but not be applicable to the current system (e.g. livepatch is `enableByDefault` but inapplicable to a system running the stock trusty kernel, because we don't publish livepatches for it). In those cases, instead of attempting to enable and displaying error messages to the user, we should simply skip the enablement step (whilst reporting that it was skipped to the user).

Open Questions:
- [x] should we report that we skipped enabling to the user?

**Comment by powersj** [comment]
> should we report that we skipped enabling to the user?

:+1:

**Comment by OddBloke** [comment]
Cool, description updated.
