### ISSUE TITLE
Upgrade path: remove old keyring files on upgrade to new uaclient

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#423]
Old uaclient delivered keyring files for esm which have now been replaced with ubuntu-esm-v2-keyring.gpg. 

Given that v1 of the esm keyring file was replaced because it was viewed as compromised, uaclient should either remove that keyring file on upgrade from oldclient to newclient. As of 4/16/2019, production and staging repositories are signed only by esm-v2 gpgkey.

**Comment by powersj** [comment]
Marking blocker for next release
