### ISSUE TITLE
`ua enable fips` fails because our shipped key doesn't match production

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#438]
When running `ua --debug enable fips`, I see the following two lines in the output:

```
[DEBUG]: Ignoring aptKey directive '13CB4B13'
[ERROR]: Invalid APT credentials provided for https://esm.ubuntu.com/fips
```

That key is:

```
$ gpg --recv-keys 13CB4B13
gpg: key 0x4067E40313CB4B13: "Ubuntu Extended Security Maintenance Automatic Signing Key v2 <esm@canonical.com>" not changed
```

Whereas the FIPS key we ship is:

```
$ gpg --list-keys --keyring keyrings/ubuntu-fips-keyring.gpg --no-default-keyring
keyrings/ubuntu-fips-keyring.gpg
--------------------------------
pub   rsa4096/0xF6C280178D13028C 2017-01-09 [SC]
      A166877412DAC26E73CEBF3FF6C280178D13028C
uid                   [ unknown] Launchpad PPA for ubuntu-advantage
```

We need to ensure that this is the correct key for FIPS in production, and then modify the key we ship to match.

**Comment by panlinux** [comment]
I believe it's failing for a different reason: the url we use to check if the credentials are valid is returning a 404:
```
[DEBUG]: XXX ANDREAS XXX ['/usr/lib/apt/apt-helper', 'download-file', 'https://bearer:lolsecret@esm.ubuntu.com/fips/ubuntu/pool/', '/tmp/uaclient-apt-test']

ubuntu@ubuntu:~$ /usr/lib/apt/apt-helper download-file https://bearer:lolosecret@esm.ubuntu.com/fips/ubuntu/pool/ /tmp/foo
Err:1 https://bearer:lolosecret@esm.ubuntu.com/fips/ubuntu/pool/
  404  Not Found
E: Failed to fetch https://esm.ubuntu.com/fips/ubuntu/pool/  404  Not Found

E: Download Failed
```

That check is done by `apt.valid_apt_credentials()`. We didn't even get to the apt key yet, and that concern is also valid, we need to ship the key that will eventually sign this repo.

**Comment by OddBloke** [comment]
It turns out that FIPS isn't deployed in production yet; we need to hold off until it is before we do anything more on this issue.

**Comment by OddBloke** [comment]
(Removed my face until we're ready to actually address this.)

**Comment by OddBloke** [comment]
Closing this in favour of #576; if there are any problems with FIPS after the fix for that that lands, they warrant opening a new issue.
