### ISSUE TITLE
/etc/apt/preferences.d/ubuntu-fips-xenial should be removed on purge

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#439]
When purging the package, `/etc/apt/preferences.d/ubuntu-fips-xenial` is left around:
```
ubuntu@ubuntu:~$ sudo apt purge ubuntu-advantage-tools
...
The following packages will be REMOVED:
  ubuntu-advantage-tools* ubuntu-minimal*
...
Processing triggers for man-db (2.7.5-1) ...
ubuntu@ubuntu:~$ ll /etc/apt/preferences.d/ubuntu-fips-xenial
-rw-r--r-- 1 root root 66 Apr 24 19:08 /etc/apt/preferences.d/ubuntu-fips-xenial
```

**Comment by OddBloke** [comment]
AIUI, our position is that FIPS can't be disabled or cleaned up. Removing that file _might_ be a reasonable thing to do but, in my opinion, leaving the system state alone entirely is probably preferable.

As such, I'm amending this to be specifically about removal on purge (and then tagging it packaging). Feel free to yell at me if you disagree!

**Comment by panlinux** [comment]
Good point about fips sticking there forever. I think it's ok to remove the file on purge, though.

**Comment by powersj** [comment]
Is this still an issue? Do I need to attach and enable fips before I can reproduce this?

**Comment by powersj** [comment]
I don't see this file with `19.5~561~git.5752542~ubuntu16.04.1`

**Comment by OddBloke** [comment]
I believe this is still an issue if you're attached and have enabled fips. Within a xenial VM with the latest PPA package installed:

```
$ sudo ua attach --no-auto-enable <token entitled to FIPS>
<snip>

$ sudo ua enable fips
One moment, checking your subscription first
Enabling authenticated repo: https://esm.ubuntu.com/fips
Updating package lists
Installing FIPS packages
FIPS enabled.
FIPS configured and pending, please reboot to make active.

$ ls /etc/apt/preferences.d/ubuntu-fips-xenial 
/etc/apt/preferences.d/ubuntu-fips-xenial

$ sudo apt purge ubuntu-advantage-tools
<snip>

$ ls /etc/apt/preferences.d/ubuntu-fips-xenial 
/etc/apt/preferences.d/ubuntu-fips-xenial
```

**Comment by OddBloke** [comment]
(This is what I was trying to reproduce when I hit a bunch of bugs yesterday, which is why I didn't get to it until this morning. :-P)

**Comment by powersj** [comment]
Can be revisited during xenial/bionic development. Closing.
