### ISSUE TITLE
Feature request - show how many licenses have been registered

### ISSUE THREAD

**Issue by kowalczykb** [CanonicalLtd/ubuntu-advantage-client#451]
At present as far as I am aware, there is no option to display how many servers were registered/activated for ESM. Our Clients would like to have this visibility. Maybe via "ua status" ?

**Comment by powersj** [comment]
Hi!

Thanks for the suggestion and I can easily see this being useful. We have some initial thoughts on approaching this via a web portal for users to see their deployments, but that is not yet finalized. We can leave this open to provide future updates.

Thanks!

**Comment by powersj** [comment]
Sometime tomorrow https://ubuntu.com/advantage will be updated as the new portal for getting your token for the client. On that site, the number of deployed machines will be present. I do not expect to add this to the client. Therefore, I am going to close this. Thanks again for the feedback and glad to see the suggestion make it in.
