### ISSUE TITLE
ua status entitlement for canonical employees better placeholder

### ISSUE THREAD

**Issue by dpb1** [CanonicalLtd/ubuntu-advantage-client#472]
```
root@trusty-test:~# ua status
Account:
Subscription:
Valid until: n/a
Technical support level: n/a

cc            entitled         n/a
cis-audit     none             n/a
esm           entitled         active
fips          entitled         n/a
fips-updates  none             n/a
livepatch     entitled         n/a

Enable entitlements with `ua enable <service>`
```

I see the above, I'd like to see `Account` and `Subscription` filled in, even with generic 'Canonical Employee' type account placeholders.

**Comment by OddBloke** [comment]
These are the lines I see after doing a `ua attach`:

```
# ua status
Account: daniel.watkins@canonical.com
Subscription: daniel.watkins@canonical.com
Valid until: n/a
Technical support level: n/a

<snip>
```

The code which generates this output is also a very thin wrapper around responses from the contract server; is it possible that the user you're using is configured in a way that would cause the contract server to return empty strings for the name fields in each of `accountInfo` and `contractInfo`?

**Comment by OddBloke** [comment]
@dpb1 has confirmed that this is a data issue for his user, not a client issue. Please do reopen if that isn't the case!
