### ISSUE TITLE
https://auth.contracts.canonical.com/ copy buttton not working

### ISSUE THREAD

**Issue by cloud-padawan** [CanonicalLtd/ubuntu-advantage-client#477]
Following the instructions to get token from https://auth.contracts.canonical.com/ ,  I noticed pressing the copy button did not function. I had to highlight the token and copy manually.

**Comment by cpaelzer** [comment]
Sorry @cloud-padawan, I filed the same issue and added much more detail to #483 before I saw this bug. Can we close this as a duplicate to #483 please?

**Comment by OddBloke** [comment]
Thanks @cloud-padawan and @cpaelzer; closing this out as a duplicate.
