### ISSUE TITLE
Make the log file we write only readable by root

### ISSUE THREAD

**Issue by cpaelzer** [CanonicalLtd/ubuntu-advantage-client#479]
Hi,
I have wondered if there is "too much" potentially sensitive info in the logs right now.
I have read #286 and #287 but none really was about the problem that I see.

Checking my log at least the following I'd only expect root to be able to see/read:

- `'accountInfo': {'id': 'a...`
- `'Authorization': 'Bearer m...`
- `'machineId': 'ee...`
- `'Authorization': 'Bearer C1`

In the case of using `ua attach <token>` the full token is seen in this log (at the POST request).
If using `ua attach` to enter credentials it is missing.
But IMHO even machine and Auth IDs are sensitive.

With that an non-admin employee in a company could steal e.g. the key of the companies account and register other machines eventually causing harm to the contract.

We can either filter much more or change `/var/log/ubuntu-advantage.log` from 644 to 600 which avoids that we miss one detail and that we later on add another one.

**Comment by powersj** [comment]
@OddBloke, did #507 close/fix this?

**Comment by OddBloke** [comment]
@powersj #507 addressed the data in /var/lib/ubuntu-advantage; this issue is regarding what we log (and/or who can read those logs).

**Comment by OddBloke** [comment]
IMO, we should change the log to only be root-readable; users who can't gain root privileges can't do anything useful with the log anyway (because they can't run any `ua` commands), so we're only leaving ourselves open to bad things happening by having it world-readable.

What do you think, @blackboxsw @powersj @cpaelzer?

**Comment by powersj** [comment]
+1 root readable only log

**Comment by panlinux** [comment]
I'm also getting the actual repository secret from `/etc/apt/auth.conf.d/90ubuntu-advantage` logged into `/var/log/ubuntu-advantage.log`, perhaps because debug level logging is enabled by default (see issue #577 )

**Comment by powersj** [comment]
I'm marking this blocker and tracking for the current release, this is a quick, easy win we should do before shipping.
