### ISSUE TITLE
A way for the admin to check "which ID" was registered

### ISSUE THREAD

**Issue by cpaelzer** [CanonicalLtd/ubuntu-advantage-client#481]
Hi,
there currently seems to be no way for an admin to check "which token" was registered.
While in a perfect world there never will be confusion and an admin should only have one contract we know it will happen sooner or later e.g. companies with different contracts for different machines then fusing their computing center or any other such scenario. Long story short, there is no way to get (other than reading json files) the machine-id and contract token that is used.

I'd request that `ua status --verbose` would report such extra info like:
```
ubuntu@trusty-ua:~$ ua status
[...]
Technical support level: n/a

Machine-ID: 2345...
Contract-Token: 5432...

cc            entitled         n/a
cis-audit     none             n/a
[...]
```

That will allow admins e.g. to check all their machines if they are on the new unified contract in above use-case example.

A bit related to #419 where @dpb1 asked for other data in `ua status --verbose`.

**Comment by OddBloke** [comment]
I'm going to close this out in favour of #419 (where I've added a note about this request).
