### ISSUE TITLE
use columns for first set of ua status information as well

### ISSUE THREAD

**Issue by cpaelzer** [CanonicalLtd/ubuntu-advantage-client#482]
Today on `ua status` and the multiple times discussed `ua status --verbose` we have:

Not so readable
```
Account: christian.ehrhardt@canonical.com
Subscription: christian.ehrhardt@canonical.com
Valid until: n/a
Technical support level: n/a
```

Nice and readable:
```
cc            entitled         n/a
cis-audit     none             n/a
esm           entitled         active
fips          entitled         n/a
fips-updates  none             n/a
livepatch     entitled         n/a

```

I'd suggest to columnize the upper output as well to something like
```
Account                   christian.ehrhardt@canonical.com
Subscription              christian.ehrhardt@canonical.com
Valid until               n/a
Technical support level   n/a
```

**Comment by dpb1** [comment]
My first reaction: I like the way key/value data is set distinct from the tabular data and feel this suggestion muddies it.  I'd like mpt's read on it though.

**Comment by matthewpaulthomas** [comment]
I can see that lining up the values would make it easier to answer questions like “Are the account and the subscription using exactly the same e-mail address”.

Key-value data could still be distinct from tabular data in two other ways:
- keys could still end with colons, while table values don’t
- keys could be right-aligned, which would also avoid the problem where short keys are far away from their values.
```
                Account: christian.ehrhardt@canonical.com
           Subscription: christian.ehrhardt@canonical.com
            Valid until: n/a
Technical support level: n/a
```
