### ISSUE TITLE
Exit on network connectivity issues during enable

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#492]
If there is no network connection on a machine, ua enable should not proceed to try enabling a support service:

```
 sudo ua enable livepatch
ERROR: Could not refresh machine token. <urlopen error [Errno 101] Network is unreachable>
Installing canonical-livepatch snap... 
ERROR: Failed running cmd: snap install canonical-livepatch, rc: 1 stderr: b'error: cannot install "canonical-livepatch": Post\n       https://api.snapcraft.io/v2/snaps/refresh: dial tcp: lookup\n       api.snapcraft.io on 10.162.96.1:53: server misbehaving\n'
```

**Comment by blackboxsw** [comment]
Ua client should stop and exit non-zero on failure to 'refresh' prior to enabling the service as that will also fail.

**Comment by OddBloke** [comment]
As mentioned in my comment on #574, I'm 100% sure that this is actually desirable behaviour.

**Comment by blackboxsw** [comment]
As agreed in #574, we **want** to proceed if there is an intermittent outage of ua-contracts sever as the contract will most likely not have changed anyway. So, no need to interrupt the user enabling their service if the rest of the service endpoints could be up and running appropriately.
