### ISSUE TITLE
Missing option to hide livepatch notification icon

### ISSUE THREAD

**Issue by Videonauth** [CanonicalLtd/ubuntu-advantage-client#493]
There is currently no option to hide the livepatch notification icon in gnomes top bar in the software and updates application.

![Selection_424](https://user-images.githubusercontent.com/9640109/57583178-3d2daf80-74ce-11e9-97ef-73fe6c92448c.png)

The only way right now as stated in the following AskUbuntu Q&A is a call to dconf either editing or via terminal:

https://askubuntu.com/questions/1140848/hide-livepatch-indicator-in-top-panel

**Comment by OddBloke** [comment]
Hi @Videonauth, 

Thanks for using Ubuntu and taking the time to file this bug! I don't believe that this is an issue with ubuntu-advantage-client. I _think_ it's a bug with the `update-notifier` Ubuntu package; please run `ubuntu-bug update-notifier` to report a bug against that package.

Thanks again!

Dan
