### ISSUE TITLE
more secrets in in /var/lib/ubuntu-advantage

### ISSUE THREAD

**Issue by cpaelzer** [CanonicalLtd/ubuntu-advantage-client#494]
This is an extension of issue #254 but forked here to not be lost.

There still are things in the world readable `-rw-r--r--` form at /var/lib/ubuntu-advantage/
It seems most moved to the private subdir, but are we sure that 
```
{"machineToken": "mAg...
"accountInfo": {"id": "aAM...
"aptKey": "1...
...
```
are not sensitive at all?
In most companies such subscriptions are usually handled with very limited access.
Posting here to reconsider if we'd want to move "more" (or since we only run as root just all) into the private subdir.

@OddBloke said:

> I'm not in a position to comment about whether these pieces of information are sensitive, but I will note that we explicitly do support running ua status as a non-root user.

Then I returned:

Interesting @OddBloke , what is the concept for the authentication then for the non-root users to be allowed to:
a) see
b) control
ua configuration?

IMHO a random user on a system with UA will at most be allowed to barely see that it is running and what is enabled. But even the account name it is on would be sensitive I'd think. Even more so all that is discussed for a status --verbose.

And for (b) obviously you'd then want some authentication, but I'm not sure which one if "access to root" isn't the way. Is there and pointer about the design/intention in that regard?

**Comment by OddBloke** [comment]
My current understanding is that we want `ua status` to work for non-root users; I wonder if we should switch from redacting the JSON files in to the non-private directory to instead generating a serialised version of the status output, and having only that be world-readable.

This would avoid us having to be mindful of what ends up in these files in the future, as well as clearing up this current issue.

**Comment by cpaelzer** [comment]
Good idea @OddBloke 

But at the same time I guess we don't want it to work for **any** non-root user.
How will authentication be made for that then?
If this design decision is already made it would have major influence on this bug discussion here.

**Comment by OddBloke** [comment]
For clarity, there's been no suggestion that this *shouldn't* be available for all non-root users.
