### ISSUE TITLE
livepatch attemptes to be enabled on Trusty GCE

### ISSUE THREAD

**Issue by powersj** [CanonicalLtd/ubuntu-advantage-client#495]
The client currently is trying to enable livepatch on GCE. It should not do that.

**Comment by panlinux** [comment]
What's the output of `uname -r` on a GCE instance?

**Comment by OddBloke** [comment]
trusty doesn't have a custom GCE kernel, so livepatch is supported; I don't think this is a bug, unless I'm missing some extra context. (Obviously, feel free to reopen if I am.)

**Comment by powersj** [comment]
My bad, you are correct. It uses a generic kernel, so technically it is allowed.
