### ISSUE TITLE
On personal accounts hide 'valid till' and 'technical support' fields

### ISSUE THREAD

**Issue by powersj** [CanonicalLtd/ubuntu-advantage-client#501]
In a review with Mark we decided that the "valid till" and "technical support" levels should be hidden from view on personal accounts. This is because they will always show "n/a" and it does not lead to a good experience.

Keep in mind though, that non-personal accounts should still show these fields, even if they are empty/null/n/a.

**Comment by OddBloke** [comment]
Looking through the data we currently pull down from the contract server, it's not clear to me how we would identify a "personal" account. I believe we'll need changes to the contract server to clearly surface this information.

(I only have ready access to one Ubuntu SSO account, so I haven't been able to check if e.g. the contract ID for the free tier is static across users. Regardless, I don't think we would want to hardcode such an ID in to the client, as that will make changing it in future fraught.)

**Comment by OddBloke** [comment]
This may be closely related to #486; I'm going to remove my face from this and see where #486 gets us to before spending any more time on this.

**Comment by powersj** [comment]
I want this fixed on the backend before we make a change. Please file a bug on contracts backend to track the work required there.
