### ISSUE TITLE
Clean up 401 messages on bad password/username

### ISSUE THREAD

**Issue by powersj** [CanonicalLtd/ubuntu-advantage-client#504]
When logging in via SSO, do not print all the massive messages. Simply say something like "Invalid username or password". I would check what `snapcraft login` shows or something similar.

The 3 large messages and the 401 message were too much

**Comment by OddBloke** [comment]
Hey Josh,

When I fail to attach (I've tried invalid email, invalid password and invalid 2FA token; all present with the same format, just a different message after "Bad Request:"), I don't see 3 large messages (unless, I guess, "ERROR", "HTTP Error 400" and "Bad Request" are the messages?):

```
# ua attach
Email: lolno
Password: 
ERROR: HTTP Error 400: Bad Request: Enter a valid email address.
Could not attach machine. Unable to obtain authenticated user token
```

Regardless, I think we can still do better by condensing this to a single error line; this is what `snapcraft login` errors look like:

```
$ snapcraft login
Enter your Ubuntu One e-mail address and password.
If you do not have an Ubuntu One account, you can create one at https://snapcraft.io/account
Email: lolno
Password: 
Authentication error: Failed to get unbound discharge: Invalid request data
```
