### ISSUE TITLE
For non-root users, make it clear that `ua status` is using cached data

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#506]
When `ua status` is run by a user other than root, it relies on data cached in the config data directory. Some of this cached data reflects the status of a service, which can change without `ua` ever running (and therefore without us ever having the opportunity to update the cache).

We should consider emitting a message for non-root users, to make it clear they should run as root to get a more accurate status.

(Currently, the cache is only used for "enabled", but once #494 is fixed, the cache will be used for all data, perhaps making this more of a pressing issue.)

**Comment by OddBloke** [comment]
@powersj This is an idea, rather than something I think we should definitely do; it's a simple change if we do want to do it.

**Comment by powersj** [comment]
> which can change without ua ever running

Can you provide an example of this?

**Comment by OddBloke** [comment]
@powersj A few examples: someone uses `canonical-livepatch` to change the livepatch state, someone removes apt auth configuration, or the applicability of an entitlement changes due to system changes (e.g. booted in to different kernel or dist-upgrade, as we've discussed before in #368).

**Comment by OddBloke** [comment]
A concrete example of where I've seen the cache cause incorrect reporting to a non-root user: `ua enable fips` will report `pending` until a reboot happens; after the reboot, the cache still has `pending` until `ua status` runs to update it to `active`.

**Comment by powersj** [comment]
We covered this in our review of the UX. Going forward we will say something is enabled as soon as it is setup. If a reboot is required, rather than showing pending, we will say enabled, but set the reboot flag. I am closing this as I feel we are following that spec.
