### ISSUE TITLE
Write preferences.d to disable ESM repository rather than magic

### ISSUE THREAD

**Issue by julian-klode** [CanonicalLtd/ubuntu-advantage-client#520]
Since Packages-Require-Authorization did not work very well, let's do manual pinning instead when adding the ESM repo:

We'd want to have

```
Package: *
Pin: ...
Pin-Priority: never
```

where ... describes the repo as we do now for some I think.

and an appropriate ua client Depends on apt (>= in -updates) so apt understands it.

**Comment by julian-klode** [comment]
Oh it just popped into my mind: The Depends probably needs to be on `libapt-pkg<abi> (>= version)`, not on `apt`.

**Comment by panlinux** [comment]
@julian-klode , given that libapt-pkg<abi> is different across ubuntu releases, is there a way to make this automatic, by having the apt hook perhaps use a specific symbol of that library, or are we better off using substvars in the packaging for now, and have a static mapping between libapt-pkg<abi> and ubuntu releases in the debian/rules file?

**Comment by julian-klode** [comment]
We do not have any specific symbol introduced in that version, so hardcoding that stuff for now seems to be the easiest option.
