### ISSUE TITLE
Stop using the logging framework to communicate errors to the user

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#526]
### Problem Statement

When investigating #504, I found that modifying the way that we display error messages is currently quite difficult, because our error output is performed through a combination of calls to `logging.error` and calls to `print`, often several frames of execution away from one another.

In the specific case of the error messages that we care about in #504, we output to the user using `logging.error` in (at least) three different places, spread across two functions; we also output a general "something went wrong" error message (via `print`) from the top-level `action_attach` function.

### Proposal

Instead of calling `logging.error` when we hit an error, I propose that we instead raise an exception which has the specific semantic meaning of "this error should be seen by the user". The main function would be wrapped in a decorator that knows how to handle these exceptions, and would format the errors in a consistent fashion.

More concretely, any part of the codebase could cause a consistently formatted error to be output by calling `raise UserFacingError("<error message>")`. The `handle_errors` decorator would catch `UserFacingError` and format it for output. Each of the `action_*` functions in CLI would be wrapped with `handle_errors` (outside of any other decorator, so that those decorators can `raise UserFacingError` themselves without it leaking out).

(If this sounds familiar, it's because this is [exactly how click handles communicating errors](http://click.palletsprojects.com/en/7.x/exceptions/). All credit to the click team for this idea.)

### Sign-off

* [x] @blackboxsw 
* [x] @powersj

**Comment by OddBloke** [comment]
@blackboxsw @powersj Please review and leave your thoughts!

**Comment by OddBloke** [comment]
In #537, we introduced a top-level error handler; that would be the natural place for this error handling to be added.

**Comment by blackboxsw** [comment]
Yes this is really a good idea and should simplify the code base quite a bit.

**Comment by powersj** [comment]
+1

**Comment by OddBloke** [comment]
The supporting work for this has landed, so I'm going to close it out. As we identify areas of interaction with the user which need tightening up, we should also migrate them to the new style of interaction.
