### ISSUE TITLE
SSOAuthError and ContractAPIError should be merged

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#530]
The two implementations are almost identical; they should be merged (perhaps using a super-class, if they need to retain separate identities).

**Comment by powersj** [comment]
SSO is no longer in the code base and exceptions are gone! Closing!

**Comment by OddBloke** [comment]
I've opened #889 to capture some of the fallout from SSO removal that wasn't fully cleaned up.
