### ISSUE TITLE
--debug status complains about private/accounts.json not existing

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#585]
`ua status` complains about this file not existing:
```
root@trusty-ua:~# ua --debug status
DEBUG: File does not exist: /var/lib/ubuntu-advantage/private/accounts.json
(...)
```
Without `--debug`, that complaint goes to `/var/log/ubuntu-advantage.log`.

What is this file about, and when is it going to be there? Or maybe is this an oversight, maybe related to the move from `/var/lib/ubuntu-advantage` to `private/`?

**Comment by OddBloke** [comment]
I've confirmed that this occurs when you attach without using SSO, and is a harmless cache miss (we fall back to using the machine token).
