### ISSUE TITLE
update d/changelog for the 19.5 release

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#614]
While we go over the changes since 19.4, here is a list of what I noticed by going over the debdiff:

- re-exported gpg keys on trusty, so that trusty can read them
- moved all sensitive state files to a private directory
- cache ua status output so unprivileged users can run it
- new ua command: refresh, to refresh contract details
- beginning i18n work for the apt hook
- updated gpg keys for fips, XXXXXwhatelse?XXXX
- common criteria (cc) short name changed to cc-eal
- log file is now only readable by root
- manpage updates

**Comment by panlinux** [comment]
SRU bug: https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1832757

**Comment by panlinux** [comment]
We can also close this one: https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1759258

**Comment by panlinux** [comment]
https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1769258 can also be closed

**Comment by panlinux** [comment]
https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1829788 can also be closed

**Comment by panlinux** [comment]
https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1777878 can also be closed

**Comment by panlinux** [comment]
By "closed", I mean closed via an entry in `d/changelog` referencing the bug.

**Comment by panlinux** [comment]
One more: https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1769258

**Comment by blackboxsw** [comment]
Closed via #617
