### ISSUE TITLE
ubuntu-securitybenchmarks-keyring.gpg is empty

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#616]
![tenor](https://user-images.githubusercontent.com/62736/59459859-ceed4d00-8deb-11e9-84f3-c079ff4d207e.gif)

(We either shouldn't have it in the repo (and modify the code that relies on it), or it should have some content.)

**Comment by OddBloke** [comment]
At the moment, no-one can enable CIS, so they won't run in to any problems. We can wait until we have a valid key to use.

**Comment by powersj** [comment]
As this is for cis-audit, I am going to move this out to 19.7 milestone.

**Comment by powersj** [comment]
We will fix this once cis-benchmark is actually available. At which point a bug with all the required items will be opened. Closing this for now.
