### ISSUE TITLE
backtrace when detaching while on an unsupported kernel for livepatch

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#621]
This is a bug in livepatch client I believe, and I filed https://github.com/CanonicalLtd/livepatch-client/issues/107. Also filing it here to see if there is something we can, or should, do about it.
The whole setup is described in the above bug, but this is the situation I have:
Running kernel:
```
ubuntu@trusty-ua:~$ uname -a
Linux trusty-ua 3.13.0-170-generic #220-Ubuntu SMP Thu May 9 12:40:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
ua status says livepatch is disabled:
```
root@trusty-ua:~# ua status
Account: panlinux@gmail.com
Subscription: panlinux@gmail.com

SERVICE
cc-eal        none             n/a
cis-audit     none             n/a
esm           entitled         inactive
fips          none             n/a
fips-updates  none             n/a
livepatch     entitled         n/a

Enable entitlements with `ua enable <service>`
```
canonical-livepatch doesn't seem to agree:
```
root@trusty-ua:~# canonical-livepatch status
client-version: 9.3.0
architecture: x86_64
cpu-model: QEMU Virtual CPU version 2.5+
last-check: 2019-06-14T13:35:51Z
boot-time: 2019-06-14T13:35:40Z
uptime: 1m14s
status:
- kernel: 3.13.0-170.220-generic
  running: true
  livepatch:
    checkState: checked
    patchState: nothing-to-apply
    version: ""
    fixes: ""
```
If I try to detach, I get a backtrace, because `snap remove` fails:
```
root@trusty-ua:~# ua detach
ERROR: Failed running command 'snap remove canonical-livepatch' [exit(1)]. Message: b'error: system does not fully support snapd: you need to reboot into a 4.4\n       kernel to start using snapd\n'
Traceback (most recent call last):
  File "/usr/bin/ua", line 9, in <module>
    load_entry_point('ubuntu-advantage-tools==19.5', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 394, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 423, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 60, in wrapper
    return func(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 230, in action_detach
    ent.disable(silent=True)
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/livepatch.py", line 132, in disable
    util.subp(['snap', 'remove', 'canonical-livepatch'], capture=True)
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 265, in subp
    out, err = _subp(args, rcs, capture)
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 238, in _subp
    stderr=err)
uaclient.util.ProcessExecutionError: Failed running command 'snap remove canonical-livepatch' [exit(1)]. Message: b'error: system does not fully support snapd: you need to reboot into a 4.4\n       kernel to start using snapd\n'
```
Indeed it does:
```
root@trusty-ua:~# snap remove canonical-livepatch 
error: system does not fully support snapd: you need to reboot into a 4.4 kernel to start using
       snapd
```
Now I can only detach, or disable livepatch, if I reboot into a supported kernel.

**Comment by powersj** [comment]
On detach, why are we cleaning up livepatch when it was not enabled in the first place?

My thinking is, if someone installs the livepatch client, it should stay on the system and when we detach we shouldn't be "cleaning up" any entitlement that wasn't enabled.

**Comment by panlinux** [comment]
It was enabled. The sequence of events was:
- on the 4.4 kernel, `ua enable livepatch`
- reboot into 3.3 kernel
- ua detach

**Comment by OddBloke** [comment]
To be clear, `ua status` is not telling you that livepatch is enabled or disabled, it's telling you it's inapplicable to the current system state. (We didn't/haven't yet bubbled the new status axes up in to the status we display to the user, so we're still following the UX in the original spec.)

(The difference in behaviour here as a result of the status axes work is that we try to disable it at all; previously, we wouldn't have even attempted that.)

**Comment by OddBloke** [comment]
Also, to clarify, the issue isn't an unsupported kernel _for livepatch_, it's an unsupported kernel _for snapd_, so we don't even get as far as running any `canonical-livepatch` commands.

**Comment by powersj** [comment]
I'm not clear on what the action is here for the client? Can that please be clarified or this closed?
