### ISSUE TITLE
refresh the status cache on reboot?

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#622]
Should we refresh the `ua status` cache on a reboot? I noticed a discrepancy between the cache and the real status when I rebooted a trusty machine. It had livepatch enabled (it was on a 4.4 kernel) but I rebooted it into a 3.3 kernel, which invalidates livepatch. `ua status` kept saying livepatch was enabled, but `sudo ua status` disagreed, and also updated the cache, so after that both started saying livepatch was disabled.

**Comment by OddBloke** [comment]
This will also occur after you enable FIPS{ Updates,} and reboot in to linux-fips; `status` will still be using the cache from before reboot (and therefore report "pending" for the entitlement that is really now active).

This seems reasonable to me.

**Comment by powersj** [comment]
If we did not have the cache, and required everyone to run status as root, would this be an issue?

**Comment by OddBloke** [comment]
Nope, root always gets fresh data, so this would not be an issue.

**Comment by powersj** [comment]
If I recall correctly, we cache data for the `ua status` command, primarily due to ESM. Did the recent changes to how we pin for ESM make it so we did not need to cache anymore?

**Comment by OddBloke** [comment]
Assigning to myself to double-check if we do need the status cache.

**Comment by OddBloke** [comment]
So I'm not sure about the pinning, but when we switched to using the status cache we removed all other public data, so we _do_ need the cache for reporting status.

(I think you're thinking of the older iteration of the cache, where we just cached the enabled status of each entitlement. We moved to a full cache of the status JSON after that.)

**Comment by powersj** [comment]
-1 on increasing what the client does. Only issue is very specific odd ball cases. I am more inclined to make someone run `sudo ua status` over adding startup scripts to the client.
