### ISSUE TITLE
uaclient: Allow for different GPG keys per series in ESM archive

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#624]
In https://github.com/CanonicalLtd/ua-contracts/issues/319, IS requested the ability to use different GPG keys for different series in ESM. As the client currently ignores the server's `aptKey` directives and installs a single keyring for each entitlement, this is something we'll need to respond to also.

**Comment by OddBloke** [comment]
The easiest fix for this would be to include the keys for every series in the one keyring file we install. This, however, somewhat defeats the point of having separate keys, so is less than ideal.

**Comment by OddBloke** [comment]
This is a proposal for a more robust solution, which doesn't rely on the `apt-key` command (or even keyservers), but would honour the `aptKey` directive:

Instead of shipping one keyring per-entitlement, ubuntu-advantage-client will instead ship each key that we know to be trusted separately, identified by its key ID. When we are enabling an entitlement, we will use the `aptKey` directive to select which of these shipped keys we use and import it in to the keyring at the path we would currently copy our keyring to.

(This separate key shipping could be a single keyring with every key, or we could ship the keys ASCII-armored for easier of import on the target system, or we could do something else; the important aspect is that we can index in to whatever storage we're using by key ID.)

**Comment by OddBloke** [comment]
(Having said that it doesn't matter how we ship the keys, separate files on disk would mean that we would be tightly coupled to the exact key ID format that the contract server provides. If they moved between short IDs, long IDs or fingerprints, things would break. So that's probably an argument for using `gpg` to select the keys from a single keyring.)

**Comment by OddBloke** [comment]
(We should ensure that whatever solution we come up with for this will support key rotation.)

**Comment by powersj** [comment]
Based on another thread and discussions around what the client should do it seems:
1) The client will be the mechanism for shipping keys for the UA client
2) If keys need to be updated, it involves an update to the UA client it self
3) For rotation, the official keyring can be used to revoke bad keys and what would be required by the client is shipping the new key

As such I believe this means we want different keys per release. Is there a clear action for the client now?

**Comment by OddBloke** [comment]
I believe there are two parts to this: (a) handle per-series keys when we're copying keys in to `/etc/apt/...`; currently we only handle one key(ring) per entitlement, and (b) work out how we want to use the indication from the server to message to the user if we don't have the expected key available.

For (a), I believe it's still an open question as to whether or not we will hard-code the exact keys that each series for each entitlement will use, or if we will select the key to install in to /etc/apt/... at enable time based on the `aptKey` directive from the contract server. (Note that in either scenario, the keys we would consider installing would only be those that we ship with the `ubuntu-advantage-tools` package; the dynamic selection could only happen from that trusted set.)

Practically, though, as the contract server could instruct us to use a key that we don't have available to us, we will still need to have some sort of fallback hard-coding. So I think the steps look like this:

* modify the client to handle per-series keys for repo entitlements (i.e. the "primary key" for the GPG keys moves from being `entitlement` to being a compound of `(entitlement, series)`)
  * We would also ensure that we were shipping all the required keys for each series/entitlement pair
* modify the client to select the key to use from a shipped pool of keys using the `aptKey` directive from the contract server
  * This would fall back to the above behaviour if we didn't have the key indicated
* work out what we want the key rotation story to look like from a user perspective, to determine what the client should 

(None of these are absolute **must** haves for xenial/bionic, because even with the current code we could simply place all of the per-series ESM keys in to the ESM keyring and install all of them on every series. This, of course, rather defeats the point of per-series keys.)

As, we want to only install the necessary keys, we need to do at least the first step. IMO, the second step should only be done if it supports the key rotation story, as it's otherwise adding unnecessary complexity to the client.

(An alternative interim solution occurs to me, too: we could replace the ESM/$entitlement keyring at packaging/upload time to only include the key for the series we are uploading.)
