### ISSUE TITLE
Provide a way for consumers to configure timeouts

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#642]
Currently, there are a few places in the codebase where we will retry. Currently, these retries are tuned for a good interactive user experience (i.e. we will retry enough to avoid transient errors, but otherwise report back to the user enough information for them to make a sensible decision about any further retrying).

However, there are cases where `ubuntu-advantage-client` will be used in non-interactive settings (cloud-init is the most obvious current case, but by no means the only one). In these cases, it would be good to allow the consumers to specify a different timeout strategy, so that `ubuntu-advantage-client` will be more persistent in its retrying.

(The motivating example here is something else having the apt lock; reporting this to a user allows them to wait until the current lock-holding process is complete before retrying. For non-interactive cases, particularly at first boot, waiting longer would be a better strategy.)

**Comment by blackboxsw** [comment]
If our timeout exited with an unique exit code, then non-interactive installs, like cloud-init could opt to retry more than our default behavior and uaclient wouldn't need to implement a mechanism to timeouts or retries.

**Comment by powersj** [comment]
I'm a -1 on this. We should have solid defaults and things can work around this. Having different timeouts will lead to differences in behavior, making it difficult to resolve bugs.

**Comment by OddBloke** [comment]
IMO, we have bimodal usage: interactive and non-interactive. There are no solid defaults which will cover both of those use cases: we will either have to compromise on the amount of time an interactive user sits around waiting to find out that something went wrong, or compromise on the reliability/ease of implementation of non-interactive use cases. (I think it's pretty clear that we should compromise in favour of the interactive use case, as that will be how most people experience `ua` for the first time and we want that first experience to be positive.)

I also think it's worth noting that the "things" in this case are more often than not going to be customers, having to work out how to roll UA out across their fleet using puppet/chef/ansible/SSM/WALinuxAgent custom commands/their own hacked up internal thing/whatever. I'm not trying to draw a line in the sand or saying that we _need_ to implement different timeout behaviour within the client given this, but I would like us to be sure that we can't come up with something that would save all of these different silos from having to work out retrying independently.

Would you feel differently about this proposal if instead of allowing people to specify the exact timeout they want in seconds or whatever, we simply provided a way to switch to a non-interactive timeout mode, which would have longer-timeout behaviour that we defined? This would give us two well-defined different sets of behaviour that we could exercise in testing ahead of time, instead of a cornucopia of different timeouts.

(An alternative would be to retain the current timeouts (with some tweaks to output/return codes), and once we've implemented the retrying in cloud-init, document that well so people can easily implement it in their own systems. Customers would have to do more work than passing in a command-line option, but wouldn't be entirely on their own.)

**Comment by powersj** [comment]
> Would you feel differently about this proposal if instead of allowing people to specify the exact timeout they want in seconds or whatever, we simply provided a way to switch to a non-interactive timeout mode, which would have longer-timeout behaviour that we defined?

I would feel better if we had a data showing this is a problem and with something that clearly gave us something to work towards. This does not seem actionable yet, which is why I am inclined to close and we can revisit as we get more users and find issues.

**Comment by OddBloke** [comment]
I think it is actionable (add a `--longer-timeouts-please` option after deciding on a good name for it, and have that toggle the list of retry durations that we use when retrying), but I definitely agree it would be better to be driven by user/customer demand for this.

(We should definitely do some testing of the cloud-init integration, to see if we can trigger anything that might need this there.)
