### ISSUE TITLE
Write tooling for creating changelogs

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#652]
Following from a discussion on IRC, we want tooling that allows us to do the following with changelog entries:

* create them at the same time that the change is being made
* make it possible for CI to detect (and reject) PRs that don't contain a changelog entry
* create changelog entries in parallel without creating merge conflicts
* allow modification of changelog entries at any point after they have been created

A couple of other considerations, which aren't requirements:

* an ordering on changelog entries would be good, but not at the expense of potential conflicts
* being able to bucket changelog entries by category would be good

**Comment by OddBloke** [comment]
CPython has [blurb](https://pypi.org/project/blurb/) which could be used as an example of things to think of; it is intentionally tightly-coupled to the CPython repository, so we can't use it directly.

**Comment by powersj** [comment]
-1 on this. As we did with 19.6, we cover the high-level items and go from there. No need to build heuristics of what change log items we should include or not include.
