### ISSUE TITLE
client assert aptKey fingerprint directives match static key provided in ua-tools package and suggest the user update the ubuntu-advantage-tools package if not.

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#673]
If ua-contracts aptKey fingerprint is *not equal to* ubuntu-advantage-tools apt keys, then we have experienced and apt key rotation event for the service and ua client should warn the user that an ubuntu-advantage-tools package is out of date and that they need tto upgrade their ua-tools package.

Since ua-contracts will continue to report suggested aptKeys for hat each service. UA client should validate that the static apt key packaged in ubuntu-advantage-tools matches what is authorized via ua-contracts service. 

In the event of an apt key rotation for a specific apt-based service (esm, fips, cis-audit, cc-eal),  ua-contracts will change the aptKey fingerprint value to the new key. During a apt key rotation event,  the ubuntu-advantage-tools package would have needed to release an updated package  which will contain any new static apt keys.

**Comment by powersj** [comment]
In the event of a key rotation the ua tools package will be updated. Messages would go out to customers and broadcast rather loudly due to the large impact it would have. Therefore, I am -1 on adding more things to the client. Closing.
