### ISSUE TITLE
Enable CC-EAL

### ISSUE THREAD

**Issue by powersj** [CanonicalLtd/ubuntu-advantage-client#676]
Bug to track the enablement of CC-EAL

- [x] Get Xenial GPG Key
- [x] Ensure enable installs correct packages 
- [x] Ensure disable works and removes packages
- [x] Ensure enable only enables on Xenial
- [x] Ensure status works as root
- [x] Ensure status works as non-root
- [x] Enable, disable, and enable the service, verify status

**Comment by blackboxsw** [comment]
multipass@dev-x:~$ sudo ua enable cc-eal
One moment, checking your subscription first
ua Enabling authenticated repo: https://esm.ubuntu.com/cc
Updating package lists
Installing Canonical Common Criteria EAL2 Provisioning packages
(This will download more than 500MB of packages, so may take some time.)
Canonical Common Criteria EAL2 Provisioning enabled.
Please follow instructions in /usr/share/doc/ubuntu-commoncriteria/README to configure EAL2
multipass@dev-x:~$ ua status
                Account: UA Client Test
           Subscription: UA Client Test Contract
            Valid until: n/a
Technical support level: advanced

SERVICE
cc-eal        entitled         active
cis-audit     none             n/a
esm           entitled         active
fips          entitled         inactive
fips-updates  entitled         inactive
livepatch     entitled         active

Enable entitlements with `ua enable <service>`
multipass@dev-x:~$ sudo ua status
                Account: UA Client Test
           Subscription: UA Client Test Contract
            Valid until: n/a
Technical support level: advanced

SERVICE
cc-eal        entitled         active
cis-audit     none             n/a
esm           entitled         active
fips          entitled         inactive
fips-updates  entitled         inactive
livepatch     entitled         active

Enable entitlements with `ua enable <service>`
multipass@dev-x:~$ sudo apt-get update
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease                        
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]       
Hit:4 https://esm.ubuntu.com/cc/ubuntu xenial InRelease     
Hit:5 https://esm.ubuntu.com/ubuntu xenial-security InRelease 
Get:6 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Hit:7 https://esm.ubuntu.com/ubuntu xenial-updates InRelease 
Fetched 325 kB in 1s (294 kB/s)
Reading package lists... Done


# Ensure enable only enables on Xenial (trusty box below)
multipass@dev-t2:~$ sudo ua enable cc-eal
One moment, checking your subscription first
Canonical Common Criteria EAL2 Provisioning is not available for Ubuntu 14.04 LTS (Trusty Tahr).
