### ISSUE TITLE
Coverity reports uninit_use_in_call warning

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#686]
The output from the tool:

```
/build/ubuntu-advantage-tools-Ocxs8m/ubuntu-advantage-tools-19.5.1/apt-hook/hook.cc:53
  Checker: UNINIT

/build/ubuntu-advantage-tools-Ocxs8m/ubuntu-advantage-tools-19.5.1/apt-hook/hook.cc:46:
  1. path: Condition "pid == """, taking false branch.
/build/ubuntu-advantage-tools-Ocxs8m/ubuntu-advantage-tools-19.5.1/apt-hook/hook.cc:51:
  2. var_decl: Declaring variable "stream".
/build/ubuntu-advantage-tools-Ocxs8m/ubuntu-advantage-tools-19.5.1/apt-hook/hook.cc:53:
  3. uninit_use_in_call: Using uninitialized value "stream._M_streambuf_state" when calling "fail".
/usr/include/c++/9/bits/basic_ios.h:202:
  3.1. read_parm_in_call: The called function reads "this->_M_streambuf_state".
/usr/include/c++/9/bits/basic_ios.h:138:
  3.1.1. read_parm_fld: Reading field of 'this'.
```

**Comment by OddBloke** [comment]
@julian-klode Is this something you could take a look at addressing?

**Comment by julian-klode** [comment]
Don't see a problem here.

**Comment by julian-klode** [comment]
All variables are properly initialized, it seems to be complaining about some code in the standard C++ library. It seems to be complaining about the call to `fail()`, but giving the line number for the call to `getline()` (at least in master)?

There is a minor inconsistency in that getline() could fail and we might end up reading the previous line again or an empty line, but that's not really an issue, we'll just iterate one more time and exit the loop then.

**Comment by powersj** [comment]
It would be nice to be coverity clean, but if this is not an issue I am going to close this.
