### ISSUE TITLE
avoid duplicate sources.list entries after release upgrade

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#693]
After a do-release-upgrade from an esm-enabled precise system, to trusty, esm was still enabled at the end.

The release upgrade procedure changed the distro name in the esm `sources.list.d/` file from precise to trusty, but kept the filename. `/etc/apt/sources.list.d/ubuntu-esm-precise.list` now has:
```
deb https://username:password@esm.ubuntu.com/ubuntu trusty-updates main
```
Note how the file is still named after precise, but now contains a trusty repo, and with the old-style esm credentials. This is what is keeping this trusty system linked to esm at this point.

The problem happens once you install the new client, 19.5.1. It will, in its postinst, create `ubuntu-esm-trusty.list`, since that file doesn't exist yet. It will point at the same repository as
the already existing `ubuntu-esm-precise.list`, and we get this complaint:
```
Setting up ubuntu-advantage-tools (19.5.1~ubuntu14.04.1~ppa2) ...
W: Duplicate sources.list entry https://esm.ubuntu.com/ubuntu/
trusty-security/main amd64 Packages
(/var/lib/apt/lists/esm.ubuntu.com_ubuntu_dists_trusty-security_main_binary-amd64_Packages)
W: Duplicate sources.list entry https://esm.ubuntu.com/ubuntu/
trusty-security/main i386 Packages
(/var/lib/apt/lists/esm.ubuntu.com_ubuntu_dists_trusty-security_main_binary-i386_Packages)
W: Duplicate sources.list entry https://esm.ubuntu.com/ubuntu/
trusty-updates/main amd64 Packages
(/var/lib/apt/lists/esm.ubuntu.com_ubuntu_dists_trusty-updates_main_binary-amd64_Packages)
W: Duplicate sources.list entry https://esm.ubuntu.com/ubuntu/
trusty-updates/main i386 Packages
(/var/lib/apt/lists/esm.ubuntu.com_ubuntu_dists_trusty-updates_main_binary-i386_Packages)
W: You may want to run apt-get update to correct these problems
```
Not the end of the world, as apt still exits with status 0, but this will show up everytime apt update is run, even after ua attach is done. One cannot simply delete one of these files, as the one named after precise is the only one with the esm credentials at this point (before ua attach), and is what is keeping this system up-to-date. The proper (manual) procedure to finish the release upgrade is:
- run `ua attach`
- then delete `/etc/apt/sources.list.d/ubuntu-esm-precise.list*` (with globbing, to also remove the backup file from do-release-upgrade. These all contain credentials and are 0644)

Then apt update will be happy again.

**Comment by blackboxsw** [comment]
NOTE: On upgrade path from precise to trusty, we also need to consider unconfigure_esm behavior in debian/postinst.

During **do-release-upgrade** If /etc/os-release is **not** updated to 'trusty' before ubuntu-advantage-tools is upgraded to the new client, then we need an alternative mechanism to migrate precise apt source file to trusty apt-source file.
