### ISSUE TITLE
Align resource title and description with new ux changes

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#741]
New UX changes suggest some new descriptions for the Ubuntu Advantage services. There now are some discrepancies between service.title and service.description.

- service.name is an unique product name exposed by Contracts API service to uaclient to let us know which resource is being described.
- service.title a short human-readable title of the service that is emitted to the console during **ua --help** and **ua enable/disable** operations
    - Example console message "Installing <service.title> packages"
- service.description is a longer human-readable description of the service
    - exposed in Description column in tabular status output

Below is a table of examples per service

name  | title | description
------ | ------ | -----
esm | Extended Security Maintenance | Ubuntu Extended Security Maintenance archive (https://ubuntu.com/esm)
cc-eal | Canonical Common Criteria EAL2 Provisioning | Common Criteria for Information Technology Security Evaluation - EAL2
fips | FIPS | NIST-certified FIPS modules
fips-updates | FIPS Updates | Uncertified security updates to FIPS modules
cis-audit | Canonical Common Criteria EAL2 Provisioning | Center for Internet Security Audit Tools

**Comment by powersj** [comment]
Here are the new descriptions:

- Common Criteria EAL2 Provisioning Packages
- Center for Internet Security Audit Tools
- UA Infra: Extended Security Maintenance
- NIST-certified FIPS modules
- Uncertified security updates to FIPS modules
- Canonical Livepatch service

**Comment by powersj** [comment]
Here are my proposed titles:

- CC-EAL
- CIS Audit
- ESM Infra
- FIPS
- FIPS Updates
- Livepatch
