### ISSUE TITLE
test real SF accounts and it shows the wrong subscriptions

### ISSUE THREAD

**Issue by BryanQuigley** [CanonicalLtd/ubuntu-advantage-client#804]
and different between web interface and cl client.  ESM does not show up in the picture - as  available.

I'm guessing part of it is we aren't ready to launch many of the other bits, yet?

```
$ sudo ua status
sudo: unable to resolve host trusty-esm-2
SERVICE       ENTITLED  STATUS    DESCRIPTION
cc-eal        no        —         Common Criteria EAL2 Provisioning Packages
cis-audit     no        —         Center for Internet Security Audit Tools
esm-infra     yes       enabled   UA Infra: Extended Security Maintenance
fips          no        —         NIST-certified FIPS modules
fips-updates  no        —         Uncertified security updates to FIPS modules
livepatch     yes       n/a       Canonical Livepatch service

Enable services with: ua enable <service>
```
![ESM not showing available](https://user-images.githubusercontent.com/702754/66437455-9ac31b00-e9de-11e9-9976-ea233893c186.png)

**Comment by BryanQuigley** [comment]
It also appears to show 1 attached, but doesn't tell me how many I have. (I have more than 1 attached)

**Comment by BryanQuigley** [comment]
Oh, I only have 1 license,  is that what it's getting at?

**Comment by powersj** [comment]
@BryanQuigley thanks for trying out the client and taking the time to file a bug report.

Can you file this under the contracts project? I am going to close this as this is not a client issue.
