### ISSUE TITLE
status: add contract and account ids to --format --json for debug/triage

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#805]
It helps the contracts backend folks to triage and debug cases if contract id and account id are readily available during at bug filing time. Grabbing account/contract ids from either /var/log/ubuntu-advantage.log or /var/lib/ubuntu-advantage/private/ is likely to also have a bunch of private information that is tougher for the bug reported to scrub.

**Comment by BryanQuigley** [comment]
We already capture "ubuntu-advantage status" - https://github.com/sosreport/sos/blob/master/sos/plugins/ubuntu.py

If we can make that more useful by default that would be ideal.  Changing to json wouldn't be that hard though.

**Comment by OddBloke** [comment]
IMO, `ua status` would become less useful by adding more information that isn't of immediate use to an end user in most situations.

I would suggest that in the short-term we capture the JSON in sosreport (perhaps in addition to the normal user-facing output, to make debugging issues with status itself easier?) and in the longer-term, if we find that the JSON isn't working out for whatever reason, we could consider adding a `--verbose` or similar.
