### ISSUE TITLE
Check for livepatch availability/enablement has odd edge cases

### ISSUE THREAD

**Issue by cpaelzer** [CanonicalLtd/ubuntu-advantage-client#807]
Issues to fix:

- [X]  check container first before minKernelVersion as you can't 'fix' being in a container so don't tell people they need to upgrade
- [X] minKernelVersion check is broken as it separately compares kernMajorVer > minKernMajor && kernMinorVer > minKernelMinor   5.0 is > 4.3 :) 
- [X] Availability of livepatch should always be "no" for containers, this is really a ua-contract backend issue that I've filed for discussion @ https://github.com/CanonicalLtd/ua-contracts/issues/469
Filed separate UA Client issue for the third item above: #831 

I think we all agree that the kernel is part of the Host and livepatch will never work from inside a container.

But before subscription it shows "yes" for availability.
`livepatch     yes        Canonical Livepatch service`

Interestingly on a Trusty kernel 3.13 system it is Availability "no".
After upgrade to kernel 4.4 it becomes Availability "yes".
Shouldn't the container also report "no" here no matter what kernel version is active?

Furthermore after attaching it to my token I've seen this in the Container:
That seems to be reported ok in `ua status`
`livepatch     yes       n/a       Canonical Livepatch service`

Ok, my contract is entitled, but it isn't applicable here (that makes sense).
But when I ignore that statement and try to enable it the error is misleading:

```
ua enable livepatch
One moment, checking your subscription first
Livepatch is not available for kernel 5.0.0-29-generic.
Minimum kernel version required: 4.4
```

First: The error says "minimum 4.4" which 5.0 clearly satisfies.
Seconds: On top even if we'd have 4.4 or whatever else, it just would not work from inside a container.

I wonder if on `ua enable livepatch` there should be something like:
```
if system-detect-virt --container
   "Livepatch is unavailable, it  has to be enabled at the host where the kernel resides not in containers"
```

Note: I've found in further tests that you seem to have code for the second already.
If run on a valid kernel (Host is Trusty with 4.4):
```
root@t:~# ua enable livepatch
One moment, checking your subscription first
Cannot install Livepatch on a container
```
Maybe the just ordering of those checks needs to be improved to first check for container and only afterwards for kernel version?

Summary:
 * Availability of livepatch in unattached `ua status`  in a container should always be "no" (it is ok to be called entitled, but not available)
 * On trying to enable livepatch it it should be made clear that trying to do so in a container is in vain (code reordering?)

**Comment by powersj** [comment]
Next steps:

1) Switch ordering to check for if container first, then kernel version
2) Verify the kernel version number is getting factored correctly into the availability check (e.g. Eoan's 5.x version)
