### ISSUE TITLE
Whitespace damage in ua status -h

### ISSUE THREAD

**Issue by cpaelzer** [CanonicalLtd/ubuntu-advantage-client#808]
Really not too important, but OTOH easy to fix.

```
root@t:~# ua status -h
usage: ubuntu-advantage status [flags]
[...]
* AVAILABLE: whether this service would be available if this machine
  were attached.  The possible values are yes or no.
```

Multiple white-spaces in front of "The possible values"

**Comment by panlinux** [comment]
Some people argue that it's correct to use two spaces after a full stop. I stay out of that discussion :)

**Comment by powersj** [comment]
Decided to go back to single spaces to be consistent with other user facing messages.
