### ISSUE TITLE
Disabling esm-infra has odd and maybe unexpected effects

### ISSUE THREAD

**Issue by cpaelzer** [CanonicalLtd/ubuntu-advantage-client#809]
Knowing that `apport` is in the current esm-infra repo lets use this for a check:
Initially the system is clean trusty:

```
ua status
SERVICE       ENTITLED  STATUS    DESCRIPTION
cc-eal        no        —         Common Criteria EAL2 Provisioning Packages
cis-audit     no        —         Center for Internet Security Audit Tools
esm-infra     yes       disabled  UA Infra: Extended Security Maintenance
fips          no        —         NIST-certified FIPS modules
fips-updates  no        —         Uncertified security updates to FIPS modules
livepatch     yes       n/a       Canonical Livepatch service
root@t:~# apt-cache policy apport
apport:
  Installed: 2.14.1-0ubuntu3.29
  Candidate: 2.14.1-0ubuntu3.29
  Version table:
 *** 2.14.1-0ubuntu3.29 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     2.14.1-0ubuntu3 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
```

We see the new version of apport show up:
```
root@t:~# ua enable esm-infra
One moment, checking your subscription first
Updating package lists
ESM Infra enabled.
root@t:~# ua status
SERVICE       ENTITLED  STATUS    DESCRIPTION
cc-eal        no        —         Common Criteria EAL2 Provisioning Packages
cis-audit     no        —         Center for Internet Security Audit Tools
esm-infra     yes       enabled   UA Infra: Extended Security Maintenance
fips          no        —         NIST-certified FIPS modules
fips-updates  no        —         Uncertified security updates to FIPS modules
livepatch     yes       n/a       Canonical Livepatch service

Enable services with: ua enable <service>

     Account: christian.ehrhardt@canonical.com
Subscription: christian.ehrhardt@canonical.com
root@t:~# apt-cache policy apport
apport:
  Installed: 2.14.1-0ubuntu3.29
  Candidate: 2.14.1-0ubuntu3.29+esm1
  Version table:
     2.14.1-0ubuntu3.29+esm1 0
        500 https://esm.ubuntu.com/ubuntu/ trusty-infra-security/main amd64 Packages
 *** 2.14.1-0ubuntu3.29 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     2.14.1-0ubuntu3 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
```

Ok so far, but at least in my tests it didn't "go away"

```
root@t:~# ua disable esm-infra
Updating package lists
root@t:~# apt-cache policy apport
apport:
  Installed: 2.14.1-0ubuntu3.29
  Candidate: 2.14.1-0ubuntu3.29
  Version table:
     2.14.1-0ubuntu3.29+esm1 0
       -32768 https://esm.ubuntu.com/ubuntu/ trusty-infra-security/main amd64 Packages
 *** 2.14.1-0ubuntu3.29 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     2.14.1-0ubuntu3 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
```

This also persists through an explcit `apt update` and I have found that the file `/etc/apt/sources.list.d/ubuntu-esm-infra-trusty.list` is still in place and has not changed content.

It seems the only changes are
* pinning was set to -MAXINT
```
cat /etc/apt/preferences.d/ubuntu-esm-infra-trusty 
Package: *
Pin: release o=UbuntuESM, n=trusty
Pin-Priority: never
```
* dropping the login auth in `/etc/apt/auth.conf.d/90ubuntu-advantage`

At first that seemed a good decision to me (and I read #382 and , as that will keep the package versions and dependencies known to apt which is important if e.g. a few packages of esm-infra were already installed.

But there are a few odd effects and missing pieces to that now IMHO:

1. How would I get rid of esm-infra if I REALLY want to
    * Manually I'd think something like:
      * apt install ppa-purge
      * ppa-purge -s esm.ubuntu.com/ubuntu trusty-infra-security
   => should that be something that the UA client can do for a user?
   => This usually wouldn't be critical, but since we nowadays enable esm-infra on `ua attach` by default it is IMHO.

2. Disabling just via pinning on -MAXINT has odd effects to some tools, look at `apt list upgradable` for example:
```
apt list --upgradable
Listing... Done
apport/trusty-updates,trusty-security,now 2.14.1-0ubuntu3.29 all [installed,upgradable to: 2.14.1-0ubuntu3.29]
bash/trusty-updates,trusty-security,now 4.3-7ubuntu1.7 amd64 [installed,upgradable to: 4.3-7ubuntu1.7]
bind9-host/trusty-updates,trusty-security,now 1:9.9.5.dfsg-3ubuntu0.19 amd64 [installed,upgradable to: 1:9.9.5.dfsg-3ubuntu0.19]
```
That lists everything with the same versions and won't stop doing so (might be a bug in apt instead of UA tools, but delivering UA as-is will trigger this).

P.S. I know that I reported two issues at once, but that feels right to start the discussion.
We can split things off as an extra issue later.

**Comment by panlinux** [comment]
> Disabling just via pinning on -MAXINT has odd effects to some tools, look at apt list upgradable for example:

The `apt list --upgradable` output looks correct to me, it's not listing the esm version of apport.

Let me try on a fresh system. With ESM enabled:
```
ubuntu@trusty-ua:~$ apt-cache policy apport
apport:
  Installed: 2.14.1-0ubuntu3.29
  Candidate: 2.14.1-0ubuntu3.29+esm1
  Version table:
     2.14.1-0ubuntu3.29+esm1 0
        500 https://esm.ubuntu.com/ubuntu/ trusty-infra-security/main amd64 Packages
 *** 2.14.1-0ubuntu3.29 0
        500 http://br.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     2.14.1-0ubuntu3 0
        500 http://br.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
```
And `apt list` shows the ESM version of apport:
```
ubuntu@trusty-ua:~$ apt list --upgradable 2>/dev/null|grep ^apport
apport/trusty-infra-security 2.14.1-0ubuntu3.29+esm1 all [upgradable from: 2.14.1-0ubuntu3.29]
```
But with ESM disabled, just the normal non-esm version of apport is shown:
```
ubuntu@trusty-ua:~$ apt list --upgradable 2>/dev/null|grep ^apport
apport/trusty-updates,trusty-security,now 2.14.1-0ubuntu3.29 all [installed,upgradable to: 2.14.1-0ubuntu3.29]
```
And apt cache policy:
```
ubuntu@trusty-ua:~$ apt-cache policy apport
apport:
  Installed: 2.14.1-0ubuntu3.29
  Candidate: 2.14.1-0ubuntu3.29
  Version table:
     2.14.1-0ubuntu3.29+esm1 0
       -32768 https://esm.ubuntu.com/ubuntu/ trusty-infra-security/main amd64 Packages
 *** 2.14.1-0ubuntu3.29 0
        500 http://br.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
```

**Comment by panlinux** [comment]
About what happens to the ESM packages you installed already, when you disable ESM, I don't think that was explicitly defined. What happens right now, and which can be argued for, is that you get to keep the packages. You won't receive further updates for them, ESM or not.

**Comment by cpaelzer** [comment]
Thanks for explaining the reasoning on leaving the repo configured - that makes sense and matches what I have found.
But I continue to wonder about:

```
ubuntu@trusty-ua:~$ apt list --upgradable 2>/dev/null|grep ^apport
apport/trusty-updates,trusty-security,now 2.14.1-0ubuntu3.29 all [installed,upgradable to: 2.14.1-0ubuntu3.29]
```

This is a quote of your test result and it shows the SAME version.
This isn't upgradable at all.

It almost seems that `apt list --upgradable` ignores the pinning for selecting the list of packages to report, but then considers it when reporting the versions.

**Comment by panlinux** [comment]
Ah, you are right. It shouldn't be listing a package that can be upgraded to itself. This should be filed against the apt package/project then in LP.

**Comment by panlinux** [comment]
@julian-klode pointed out this looks like https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=753297 i.e., a bad interaction with pinning.
