### ISSUE TITLE
Update hook.cc to match UX documentation

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#823]
In `apt-hook/hook.cc`:
```c++
ioprintf(std::cout, gettext("See 'ua enable esm' or https://ubuntu.com/esm"));
```
It is printed at the end of a dist-upgrade, for example:
```
ubuntu@trusty-ua:~/git$ sudo apt dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

62 additional updates are available with Extended Security Maintenance.
See 'ua enable esm' or https://ubuntu.com/esm
```

**Comment by powersj** [comment]
The bottom line should also be updated to be consistent with other messaging:

```
62 additional updates are available with UA Infra ESM.
To see these additional updates run: apt list --upgradable
See https://ubuntu.com/advantage or run: sudo ua status
```

**Comment by OddBloke** [comment]
@powersj I agree that we should also change that text, but the two places we refer to esm-infra in the rest of the codebase are "ESM Infra" (the title) and "UA Infra: Extended Security Maintenance" (the description), so it's not 100% clear to me that your proposed update is consistent with other messaging. Should I make it "ESM Infra"?

**Comment by powersj** [comment]
Yes I agree the client uses a slightly different, but this matches and is consistent with what was decided with update-notifier output. See: https://bugs.launchpad.net/ubuntu/+source/update-notifier/+bug/1842508

**Comment by OddBloke** [comment]
@powersj Looks like that output uses "UA Infrastructure ESM" (rather than just "Infra" as the middle word), shall I go with that?

**Comment by powersj** [comment]
Yes /me goes and updated the UX doc
