### ISSUE TITLE
non-root ua status for livepatch still n/a after kernel upgrade and reboot

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#849]
On stock trusty with a 3.3 kernel `ua status` reports livepatch as "n/a" due to the kernel not meeting the minKernelVersion of 4.4.

After installing the HWE kernel on trusty on a kvm machine and rebooting into that 4.4 kernel, `ua status` should report that livepatch is  "disabled" instead of "n/a". 

But it doesn't:
```#Non-root status has incorrect livepatch status. Running status as root corrects this 
multipass@dev-t2:~$ uname -r
4.4.0-165-generic
multipass@dev-t2:~$ ua status
SERVICE       ENTITLED  STATUS    DESCRIPTION
cc-eal        no        —         Common Criteria EAL2 Provisioning Packages
cis-audit     no        —         Center for Internet Security Audit Tools
esm-infra     yes       enabled   UA Infra: Extended Security Maintenance
fips          no        —         NIST-certified FIPS modules
fips-updates  no        —         Uncertified security updates to FIPS modules
livepatch     yes       n/a       Canonical Livepatch service
```

Steps to reproduce:
```
 multipass launch daily:trusty -n dev-t;
 multipass exec dev-t sudo add-apt-repository ppa:canonical-server/ua-client;
 multipass exec dev-t sudo apt-get update;
 multipass exec dev-t sudo apt-get install ubuntu-advantage-tools;
 multipass exec dev-t -- sudo ua attach <YOURCONTRACTTOKEN>;
 multipass exec dev-t -- sudo apt-get install --install-recommends linux-generic-lts-xenial  ; 
 multipass exec dev-t sudo reboot;
 multipass exec dev-t ua status;
```

**NOTE**:  running `sudo ua status` will fix this because root-user will re-run status data collection and persist a new status-cache file that non-root uses

**Comment by blackboxsw** [comment]
one potential workaround for non-root not knowing most recent/true status values would be a job that refreshes status across reboot https://paste.ubuntu.com/p/xjvsc3fDSB/

**Comment by powersj** [comment]
We are going to close this for now as wont-fix.

First, allowing users to continue to run `ua status` as non-root is important enough. It is helpful to have even though every other command requires root. I do think there is an argument for making it so even status requires root, but that can be talked about at a later date.

Second, this case is a very rare one off. A user has to have Trust, with the non-HWE kernel, install it, and then reboot and run `ua status`. The odds of this happening are low, and telling them to run it as root, or to enable livepatch as root again, will fix this.

Third, I don't see this happening in any future release, so it would be catching a very small use-case.
