### ISSUE TITLE
"ua enable livepatch" doesn't explain how to get a compatible kernel

### ISSUE THREAD

**Issue by jetpackdanger** [CanonicalLtd/ubuntu-advantage-client#862]
In a multipass 14.04 LTS VM, with a UA subscription attached:

    multipass@normal-steelhead:~$ dpkg-query -W ubuntu-advantage-tools
    ubuntu-advantage-tools  19.6~651~git.f93c6aa~ubuntu14.04.1
    multipass@normal-steelhead:~$ sudo ua enable livepatch
    One moment, checking your subscription first
    Livepatch is not available for kernel 3.13.0-170-generic.
    Minimum kernel version required: 4.4
    multipass@normal-steelhead:~$ _

It would be useful if the client explained how to get the compatible kernel, or even offered to install it. There are various possible flavors (linux-virtual, linux-generic, etc.) so the client would have to suggest the corresponding linux-virtual-lts-xenial, etc.

**Comment by powersj** [comment]
I believe this is the only case we have so far where a specific action is required by the user to enable a service. Future services as of now with Xenial and Bionic should work out of the box.

We have a UX change to enable custom messages in the `ua status` description field that would say something similar to "Available with the HWE kernel". This is a step in the right direction, but not quite steps on how to get there.

Given the low volume on Trusty livepatch, I am going to close this as not something we want for now, but something we will monitor as we go live.
