### ISSUE TITLE
Update message

### ISSUE THREAD

**Issue by powersj** [CanonicalLtd/ubuntu-advantage-client#867]
Can we update:

```
$ sudo ua enable fips
One moment, checking your subscription first
This subscription is not entitled to FIPS.
See: https://ubuntu.com/advantage
```

to

```
$ sudo ua enable fips
One moment, checking your subscription first
This subscription is not entitled to FIPS.
For more information see: https://ubuntu.com/advantage
```

**Comment by powersj** [comment]
Basically we want to update the call to action when you subscription is not entitled to something

**Comment by OddBloke** [comment]
This is just `s/See:/For more information see:/`, right?

**Comment by OddBloke** [comment]
@powersj That last line is currently:

```
$ sudo ua enable fips
One moment, checking your subscription first
This subscription is not entitled to FIPS.
See: sudo ua status or https://ubuntu.com/advantage
```

Are you asking to drop the suggestion of running `status` too?

**Comment by powersj** [comment]
Correct, it doesn't make sense to have people go run status as an action for something they are not entitled to. A better call to action is to send them to the website to manage their subscription. Agreed?

**Comment by OddBloke** [comment]
On Fri, Oct 18, 2019 at 11:39:15AM -0700, Joshua Powers wrote:
> Correct, it doesn't make sense to have people go run status as an action for something they are not entitled to. A better call to action is to send them to the website to manage their subscription. Agreed?

Yep!
