### ISSUE TITLE
ua status: --format=json output contains unicode character string em-dash '\u2014'  instead of '—' 

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#871]
Scripts which consume `ua status --format=json` may have added complexity if parsing out cli output directly as our em-dash '—' unicode character is rendered as the full string '\u2014' instead of — when emitting content on utf-8 encoded consoles.  This results in complexity of any script that wants to handle status column output as they might have to match — or '\u2014' depending on how that script is calling ua status --format json.

Might we want to json.dumps(... ensure_ascii=False) or something similar to make sure we are rendering unicode chars where supported?

```
# Example output from ua status --format json vs other tools:
root@dev-t:~# ua status --format json | grep —
root@dev-t:~# ua status --format json | json_pp | grep —
Wide character in print at /usr/bin/json_pp line 81, <STDIN> chunk 1.
         "status" : "—",
root@dev-t:~# ua status --format json | jq "." | grep —
      "status": "—",
```

**Comment by OddBloke** [comment]
> This results in complexity of any script that wants to handle status column output as they might have to match — or '\u2014' depending on how that script is calling `ua status --format json`.

`ua status --format json` will only output the dash one way: as the encoded \u2014. Can you give examples where this isn't the case?

(Note that `jq` will convert Unicode escape sequences to the character they represent, by default. The `-a` switch stops it from doing that.)

**Comment by blackboxsw** [comment]
> > This results in complexity of any script that wants to handle status column output as they might have to match — or '\u2014' depending on how that script is calling `ua status --format json`.
> 
> `ua status --format json` will only output the dash one way: as the encoded \u2014. Can you give examples where this isn't the case?
> 
> (Note that `jq` will convert Unicode escape sequences to the character they represent, by default. The `-a` switch stops it from doing that.)

=I'm suggesting that maybe `ua status --format json` *should* convert the encoded content to the actual em-dash "—" character so that scripts that may tend to use `jq` or `json_pp` could expect to see the actual dash regardless of whether they are using other json manipulation tools.   But, maybe this is not a good suggestion.

**Comment by OddBloke** [comment]
I'm still not 100% sure I understand what the benefit of doing that is. Could you perhaps describe a situation you're thinking of where the current behaviour might cause issues?

**Comment by blackboxsw** [comment]
Good question, which thinking harder about how to reproduce this issue sheds light on the fact that that this is not an issue. My thoughts were that it would be confusing to python scripts vs bash scripts 
trying to determine if there were unentitled services from the attached status output because direct parsing of the json string would need to take into account matching '\u2014' in service 'status' value but someone in shell using jq or json_pp piped to awk would be looking at matching —.

I was thinking that maybe a script would have to deal with either — or '\u2014' if it tried to find matching services in that status category, based on whether they are direct parsing the json output with `awk` or `tr` versus `json_pp` or `jq`.  But in that case, the script will likely use one or the other set of tools and will have to 

#!/bin/sh 

I_HAVE_UNENTITLED_SERVICES=`ua status --format json | grep '\u2014'

MY_UNENTITLED_SERVICE_NAMES=`ua status --format json | jq ".services[] | select(.status == \"—\") | .name"`

That said, the script writer really only has one condition to match as they'll likely use once facility or the other..... so this is a moot point.

**Comment by OddBloke** [comment]
Further, `jq` users can just pass in `-a` (and I assume other tools have similar) to stop it from converting to the Unicode character in the first place.

Closing this out per agreement on IRC.  Thanks!
