### ISSUE TITLE
Add progress bar/status to long running commnads

### ISSUE THREAD

**Issue by patviafore-canonical** [CanonicalLtd/ubuntu-advantage-client#877]
As I was playing around with the tool, I did a `ua enable livepatch`, it seemed to take a long time when updating package lists:

```
pat@trusty-ua:~$ sudo ua enable livepatch
One moment, checking your subscription first
Installing snapd
Updating package lists  
<---- seemed to spend minutes at this step ------->
Installing canonical-livepatch snap
Canonical livepatch enabled.
```

I understand that things were happening in the background, and there was probably some network requests going on.  My concern is that I had no insight into if it was making progress or just hanging.   Is there anything we can do (progress bar, curated output, etc.) to reassure a user that progress is still being made, especially if they don't have a strong network connection?

**Comment by powersj** [comment]
This is something we want to incorporate in our next set us UX changes, but not for the initial release. The future release will come with additional services that take a long to enable and will require some time.

I am going to rename this issue and use it to track this going forward.

**Comment by powersj** [comment]
Actually this is covered by the conversation in #715, so I am going to close this. Thanks again for the report!
