### ISSUE TITLE
Installing ua does not give me tab-complete in bash

### ISSUE THREAD

**Issue by patviafore-canonical** [CanonicalLtd/ubuntu-advantage-client#879]
I was using bash to explore some UA functionality, and tab complete didn't seem to work for me.

**Comment by powersj** [comment]
What platform were you running in? what version of the package? as what user? with sudo or not, if as a normal user?

**Comment by patviafore-canonical** [comment]
Running Trusty from the Azure marketplace
pat@trusty-ua:~$ ua version
19.6~655~git.7f277d0~ubuntu14.04.1

User name was pat (no ubuntu user on system).  Was not running sudo when checking tab-complete.

**Comment by powersj** [comment]
After you installed, can you login and logout and try again?

I also launched 14.04 on Azure, installed from the PPA and found auto completion was not working initially, but after a login/logout it worked as expected. The swap was required to pick up the completion scripts.

**Comment by powersj** [comment]
I'm going to mark this closed, but let us know in either case as I've confirmed this working both in Azure and with multipass after a login/logout.
