### ISSUE TITLE
Call for testing - ua client on Trusty (not allowed to enable fips cc-eal)

### ISSUE THREAD

**Issue by andronicmihaela7** [CanonicalLtd/ubuntu-advantage-client#888]
Hi,

We have been requested to run some testing for https://github.com/CanonicalLtd/ubuntu-advantage-client/milestone/4
When you login on the website it gives you the following commands: https://pastebin.canonical.com/p/ky4RK9f7XV/
But we have been told that we shouldn't enable fips cc-eal unless there is a specific requirement for it because it can cause issues

Kind Regards

**Comment by powersj** [comment]
Thanks for this. We had an update in the works and it appears to now be live. You should now see:

```
To attach a machine: | sudo ua attach <KEY>
    To check status: | sudo ua status
```
