### ISSUE TITLE
trusty build-dep python3-flake8 is in universe

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#891]
```
$ apt-cache policy python3-flake8
python3-flake8:
  Installed: (none)
  Candidate: 2.1.0-1ubuntu1
  Version table:
     2.1.0-1ubuntu1 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
```
The package is currently not building in trusty-proposed because of the missing dependencies:
https://launchpad.net/ubuntu/+source/ubuntu-advantage-tools/19.6~ubuntu14.04.1/+build/17961402
```
Dependency wait on lcy01-amd64-006 Retry this build
    Missing build dependencies: python3-flake8
    Started 8 hours ago
    Finished 8 hours ago (took 1 minute, 1.1 seconds) 
```
We should probably drop the flake8 test in trusty and its build-dep.

**Comment by panlinux** [comment]
```
Odd_Bloke> So I think we have three options:
1) manage it downstream, in the Ubuntu packaging,
2) generate a d/control file (as andreas suggested), or
3) have separate branches for each Ubuntu release (perhaps on demand; we probably
only need a trusty branch for now?).
```

**Comment by powersj** [comment]
This was resolved correct?

**Comment by panlinux** [comment]
Via https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1849851 in trusty only as far as I know. The fix just doesn't run flake8, see https://code.launchpad.net/~ahasenack/ubuntu/+source/ubuntu-advantage-tools/+git/ubuntu-advantage-tools/+merge/374736

**Comment by OddBloke** [comment]
We've taken path (1) from the options I laid out (in Andreas' comment) above. It's important to note that this means that our PPA builds and our archive builds are _not_ the same, though the difference is minor.

Given that this only affects trusty, I think we can live with that. What do others think?

**Comment by powersj** [comment]
I'm good with this as my expectation is any upload to Trusty will be bug fixes and not whole-sale changes at this point.

Closing this and the Trusty milestone. Thank you!
