### ISSUE TITLE
Integration tests: allow disabling of cleanup

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#893]
Currently the behave integration tests cleanup every container that they launch. This is good default behaviour, obviously, but it does mean that in order to retain a container for debugging a developer has to modify the test code to disable the cleanup.

We should provide a simple way (an environment variable?) to disable cleanup.

**Comment by powersj** [comment]
I believe  #1007 is to address this

**Comment by blackboxsw** [comment]
Fixed by landing #1007
