### ISSUE TITLE
Do not use `uname` to determine architecture

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#914]
While addressing issue #911 , it came to my attention that there is a mismatch in architecture names as they are being used in the contract server and in the ua client.
The server seems to be using these names (taken from https://github.com/CanonicalLtd/ua-contracts/blob/master/products/resource-esm.yaml):
  - arm64
  - armhf
  - i386
  - ppc64le
  - s390x
  - x86_64

The client, however, uses the `uname` output:
```python
def get_platform_info() -> "Dict[str, str]":
...
    uname = os.uname()
    platform_info["kernel"] = uname.release
    platform_info["arch"] = uname.machine
```
And that is not a match for many of the architecture names that the server is using. Furthermore, it's not a match for the output of `dpkg --print-architecture` which is what userspace is actually running.
`uname -m` can be deceiving in many scenarios, like chroots.
In some cases, the difference between `uname` and `dpkg` is crazy subtle:
```
ubuntu@trusty-ppc64el:~$ uname -m
ppc64le
ubuntu@trusty-ppc64el:~$ dpkg --print-architecture 
ppc64el
```
So, with all that said, what matters in the end is to use the same name everywhere. Preferably, we should be using the same names as `dpkg --print-architechture`, as that represents the user space more accurately,

The only architecture where the output of `uname -m` and `dpkg --print-architecture` match is apparently `s390x`. Here is a list:

dpkg --print-architecture | uname -m | contract server config
-- | -- | --
arm64 | aarch64 | arm64
armhf | armv7l | armhf
amd64 | x86_64 | x86_64
i386 | i686 | i386
ppc64el | ppc64le | ppc64le
s390x | s390x | s390x

**Comment by panlinux** [comment]
That all being said, we will have a mix of clients out there. Some will be using `uname`, some will be using `dpkg --print-architecture` :/
We either have the server list all combinations, or have the client handle combinations ("aliases"?). It's messy :(

**Comment by panlinux** [comment]
BTW, this also means that esm-infra is currently broken on trusty/i386, because the client is getting i686 back from uname.

**Comment by panlinux** [comment]
We will have the server for now provide the architecture names from both `dpkg --print-architecture` and `uname -m`, see https://github.com/CanonicalLtd/ua-contracts/issues/539

**Comment by powersj** [comment]
How is this issue different from #917?

**Comment by OddBloke** [comment]
This is about how we communicate our architecture to the contract server.

#917 is about which architectures we display in the error message when you try to enable an entitlement on an architecture that it doesn't support.

**Comment by OddBloke** [comment]
This is currently blocked on resolving what the actual behaviour should be, as it turns out that the obvious, simple fix for this issue is not sufficient.
