### ISSUE TITLE
Confusing user experience with no bits entitlement

### ISSUE THREAD

**Issue by cjohnston1158** [CanonicalLtd/ubuntu-advantage-client#934]
I have logged into /advantage to get my credentials. I have a subscription listed as my account name, and then three "UA" related subscriptions:

![advantage-redacted](https://user-images.githubusercontent.com/24707086/69449869-b4ab8980-0d10-11ea-9fb9-91d101afb0e9.png)

I took my credentials from the Noble Industrial subscription and attached my machine with it. Once I did the attach I am given:

```This machine is now attached to 'Noble Industrial'

SERVICE       ENTITLED  STATUS    DESCRIPTION
cc-eal        no        —         Common Criteria EAL2 Provisioning Packages
cis-audit     no        —         Center for Internet Security Audit Tools
esm-infra     no        —         UA Infra: Extended Security Maintenance
fips          no        —         NIST-certified FIPS modules
fips-updates  no        —         Uncertified security updates to FIPS modules
livepatch     no        —         Canonical Livepatch service

Enable services with: ua enable <service>

                Account: Noble Industrial
           Subscription: Noble Industrial
            Valid until: 2020-09-30 00:00:00
Technical support level: advanced
```

I don't understand why using my credentials say that I have an advanced support level, but I'm not entitled to any of the bits. It's also very confusing that I have multiple subscriptions (one being my account, and others being products), some having access to the bits, others not having access to the bits.

**Comment by powersj** [comment]
Hi Chris,

As you will note from the web UI the Noble Industrial contract shows N/A for all the services as well. This means both the web service and the client are doing what the contract backend is telling us. Can I please get you to open a bug against the contract backend service at the link below and include the details of `ua status --format json` as well?

https://github.com/CanonicalLtd/ua-contracts/issues/new

Thanks!
