### ISSUE TITLE
Attempting to change from one subscription to another doesn't work

### ISSUE THREAD

**Issue by cjohnston1158** [CanonicalLtd/ubuntu-advantage-client#935]
I attached my machine using a subscription that apparently doesn't have any entitlements:

```This machine is now attached to 'Noble Industrial'

SERVICE       ENTITLED  STATUS    DESCRIPTION
cc-eal        no        —         Common Criteria EAL2 Provisioning Packages
cis-audit     no        —         Center for Internet Security Audit Tools
esm-infra     no        —         UA Infra: Extended Security Maintenance
fips          no        —         NIST-certified FIPS modules
fips-updates  no        —         Uncertified security updates to FIPS modules
livepatch     no        —         Canonical Livepatch service

Enable services with: ua enable <service>

                Account: Noble Industrial
           Subscription: Noble Industrial
            Valid until: 2020-09-30 00:00:00
Technical support level: advanced
```

When attempting to switch to another subscription which per the UI does have entitlement, I get the message:

```
# sudo ua attach <REDACTED>
This machine is already attached to 'Noble Industrial'.
```

It would be a much better UX if I could switch attachments rather than having to detach and then reattach. If I do have to detach prior to switching subscriptions, the ua attach message should provide a helpful indication of this.

**Comment by powersj** [comment]
Hi Chris,

I would prefer we provide better messaging. I would not expect customers to be switching between subscriptions generally. Assuming you were already attached, how about something like the following:

```
$ sudo ua attach <REDACTED>
This machine is already attached to '$subscription'
To use a different subscription first run: sudo ua detach
```

**Comment by cjohnston1158** [comment]
Hi Josh, not having a complete understanding of how it works that my
account lists multiple subscriptions, I can assume that someone may log in
and see that one of their subscriptions has more machines registered than
that subscription is entitled to and attempt to move some machines to a
different subscription. I think your suggestion though would make it easier
to understand what's going on.
-- 
Chris Johnston
Senior Engineer - Technical Operations
Canonical | Ubuntu

Timezone: AKDT
@: cJ@canonical.com
