### ISSUE TITLE
Detach notifications not being sent to ua-contracts

### ISSUE THREAD

**Issue by alnvdl** [CanonicalLtd/ubuntu-advantage-client#936]
Currently, it seems runnign `ua detach` does not trigger a call to the contract service at:

    DELETE /v1/contracts/{contract}/context/machines/{machine}

That would be necessary for invalidating machine tokens, as well as for auditing purposes.

**Comment by powersj** [comment]
@OddBloke or @blackboxsw can one of you grab this next week?

**Comment by OddBloke** [comment]
This is current in-progress by Chad, with a PR that has been reviewed (at least) once. So we're close.
