### ISSUE TITLE
Inconsistent ua status when running with/without sudo

### ISSUE THREAD

**Issue by alnvdl** [CanonicalLtd/ubuntu-advantage-client#937]
Running `ua status` without sudo right after booting a premium instance (I forgot that `ua status` also requires sudo):

    $ ua status
    SERVICE       AVAILABLE  DESCRIPTION
    cc-eal        no         Common Criteria EAL2 Provisioning Packages
    esm-infra     yes        UA Infra: Extended Security Maintenance
    fips          no         NIST-certified FIPS modules
    fips-updates  no         Uncertified security updates to FIPS modules
    livepatch     no         Canonical Livepatch service

    This machine is not attached to a UA subscription.
    See https://ubuntu.com/advantage

Well, it said it was not attached, so I ran:

    $ sudo ua attach
    This machine is already attached to '022588101030'.

And then I ran `ua status` again, this time with sudo, and now things seem to work:

    $ sudo ua status
    SERVICE       ENTITLED  STATUS    DESCRIPTION
    cc-eal        no        -         Common Criteria EAL2 Provisioning Packages
    cis-audit     no        -         Center for Internet Security Audit Tools
    esm-infra     yes       enabled   UA Infra: Extended Security Maintenance
    fips          no        -         NIST-certified FIPS modules
    fips-updates  no        -         Uncertified security updates to FIPS modules
    livepatch     yes       n/a       Available with the HWE kernel

    Enable services with: ua enable <service>

                    Account: 022588101030
               Subscription: 022588101030
                Valid until: n/a
    Technical support level: essential

And now `ua status` without sudo also works:

    $ ua status
    SERVICE       ENTITLED  STATUS    DESCRIPTION
    cc-eal        no        -         Common Criteria EAL2 Provisioning Packages
    cis-audit     no        -         Center for Internet Security Audit Tools
    esm-infra     yes       enabled   UA Infra: Extended Security Maintenance
    fips          no        -         NIST-certified FIPS modules
    fips-updates  no        -         Uncertified security updates to FIPS modules
    livepatch     yes       n/a       Available with the HWE kernel

    Enable services with: ua enable <service>

                    Account: 022588101030
               Subscription: 022588101030
                Valid until: n/a
    Technical support level: essential

**Comment by powersj** [comment]
This is a very poor initial experience. @blackboxsw  and @OddBloke, I believe it is time to get rid of caching and require sudo on status output. Thoughts?

**Comment by OddBloke** [comment]
This issue was filed based on the current trusty premium image, so I don't know if it's even valid for master any longer. That said, as we aren't being given the time to actually implement testing for this project, I think stripping out functionality that keeps regressing is our best option.

**Comment by alnvdl** [comment]
Not seeing this anymore with the latest client and images, closing this.
