### ISSUE TITLE
Add a `--assume-yes` parameter to `ua detach`

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#949]
If I want to detach a set of machines using automation, the confirmation prompt poses a real problem.

**Comment by OddBloke** [comment]
I've asked Josh and Chad in IRC if they think that `--yes` or `--assume-yes` would be preferable to `--force`, as that is more in line with what the flag will do.

**Comment by powersj** [comment]
`ua detach --assume-yes`
