### ISSUE TITLE
Clean up pro branches

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#950]
Ensure functionality introduced for ua-premium-trusty works in tip so we can drop this branch

**Comment by powersj** [comment]
Once #940 is closed, we can tag the two Pro/Premium branches and close/delete them.

* trusty-auto-attach
* demo/aws-premium

**Comment by OddBloke** [comment]
These have been tagged as `archive/trusty-auto-attach` and `archive/demo/aws-premium` respectively and deleted.
