### ISSUE TITLE
Looking for more documentation on the "enable-esm" -> "attach" changes

### ISSUE THREAD

**Issue by aashah** [CanonicalLtd/ubuntu-advantage-client#980]
Hello,

I was just looking for more background information on the change from `ua enable-esm` to `ua attach [token]`. What are some of the different security policies that came with moving to the token? I would be running this in a cloud virtual machine, so the two subcommands are pretty similar in a headless environment.

thanks

**Comment by powersj** [comment]
Hi @aashah,

Thanks for taking the time to ask about the UA command. Thus far the new tool is only available on Ubuntu 14.04 LTS (Trusty). We plan on releasing on other existing LTSes after doing a beta and allow users and others interested to try out the new workflow and provide feedback.

The primary reason of the change was to provide a much cleaner interface for enabling and disabling Canonical provided services. The new client provides a single place to view services available to a client, given a specific contract, and the current status of all those services. No longer will users need to have different sets of private PPA credentials for each service either.

The new workflow is `$ sudo ua enable <token>`. From there users can view the status of a system with the `$ sudo ua status` command. Tokens can be obtained for free users or purchased for additional support on the [Ubuntu Advantage site](https://ubuntu.com/advantage).

Hopefully that provides some additional color. If you have additional questions please feel free to reach out. I will leave this open for now.

Thanks!

**Comment by powersj** [comment]
I'm going to close this issue, but if you have additional questions please feel free to reach out. Thanks!
